### ISSUE TITLE
omd-nc rpm

### ISSUE THREAD

**Issue by dcec** [ConSol/omd#10]
Is no longer present the last omd-nc.xxxxxx.rpm on testing/rhel repository.

**Comment by sni** [comment]
it has been renamed to "newcore"

**Comment by dcec** [comment]
ok but where i found last omd newcore rpm?
last from repository is omd-1.11-nc.20140518.i386 : OMD - OpenSource Monitoring Distribution (New Cores Edition).

**Comment by dcec** [comment]
omd-2.00-newcores is present only on debian
