### ISSUE TITLE
Debian/Buster & backuped/restored site: Apache not starting because of ssl key/cert too short

### ISSUE THREAD

**Issue by wAmpIre** [ConSol/omd#100]
I tried to move an OMD site from Debian/Stretch to Debian/Buster, both OMD-Labs 3.20, with "omd backup" & "omd restore" (worked).

But on Buster OMD's Apache didn't come up again due to only 1024 bit key/cert. See ``~SITENAME/var/log/apache/error_log``:

<code>
[ssl:emerg] [pid 6138] AH02562: Failed to configure certificate 127.0.0.1:443:0 (with chain), check /omd/sites/SITENAME/etc/apache/site.cert

[ssl:emerg] [pid 6138] SSL Library Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
AH00016: Configuration Failed
</code>

Generate a new key/cert (with 2048 bits) and Apache starts again.

**Comment by sni** [comment]
Alright, so for future reference, remove the old keys and simply generate new ones:
```
%> rm etc/apache/site.cert etc/apache/site.key
%> ./bin/create_site_selfsigned_cert
```
should do the trick.
