### ISSUE TITLE
How to display Grafana inside Thruk  ?

### ISSUE THREAD

**Issue by hallux4** [ConSol/omd#103]
I have the preview from the action_url button.
But when I click on it it opens a new page.

How are you able to do it like in this pictures from the documentation ?

https://labs.consol.de/assets/2015-10-21-activate-nagflux/screenshot1.png
https://labs.consol.de/assets/2015-10-21-activate-nagflux/screenshot2.png
[![Alt text](https://labs.consol.de/assets/2015-10-21-activate-nagflux/screenshot2.png)](https://labs.consol.de/assets/2015-10-21-activate-nagflux/screenshot2.png)

Thanks for your time ^^

**Comment by sni** [comment]
you need a ssi file, for example the one we use for omd: 
thruk ssi file:
https://github.com/sni/Thruk/blob/master/ssi/status-header.ssi-pnp

naemon host/service template:
https://github.com/ConSol/omd/blob/labs/packages/grafana/skel/etc/naemon/conf.d/histou.cfg

this works best if you use histou to generate grafana dashboards on the fly.

Or have a look at OMD which comes with all that already:
https://github.com/ConSol/omd/
Then you can simply switch to grafana graphing like described here:
https://labs.consol.de/omd/howtos/grafana/

**Comment by hallux4** [comment]
I am using OMD.

So the SSI file is there.
I did try to follow the "How to" from https://labs.consol.de/omd/howtos/grafana/.

``` bash
tail -n 2 etc/mod-gearman/server.cfg
perfdata=grafana_data

In etc/nagflux/config.gcfg.

[ModGearman "example"] #copy this block and rename it to add a second ModGearman queue
        Enabled = true
        Address = "127.0.0.1:4730"
        Queue = "perfdata,grafana_data"
        # Leave Secret and SecretFile empty to disable encryption
        # If both are filled the the Secret will be used
        # Secret to encrypt the gearman jobs
        Secret = ""
        # Path to a file which holds the secret to encrypt the gearman jobs
        SecretFile = "/omd/sites/MY_SITE/etc/mod-gearman/secret.key"
        Worker = 1
```
And I added the action URL in my service definition.
```
action_url /MY_SITE/grafana/dashboard/script/histou.js?host=$HOSTNAME$&service=$SERVICEDESC$&theme=light&annotations=true
```

Do you know what I could have missed ?

**Comment by sni** [comment]
the gearman stuff is only required if you either use gearman already anyway or want to use both pnp and grafana.

What exactly isn't working?

**Comment by hallux4** [comment]
> 
> the gearman stuff is only required if you either use gearman already anyway or want to use both pnp and grafana.

Oh OK, these changes were not required.

> 
> What exactly isn't working?

The graph are working.
I was just curious on the method used to display grafana inside thruk like in the picture from this documentation:
- https://labs.consol.de/nagios/omd/2015/10/21/activate-nagflux.html

**Comment by sni** [comment]
i see, thats determined by the `action_url_target` from the cgi.cfg:

  etc/thruk/cgi.cfg:action_url_target=_blank

`_blank` opens a new window, set it to `main`, then it will open in the main frame.

**Comment by hallux4** [comment]
Thanks a lot.

I wish you a good day ;)
