### ISSUE TITLE
how to disable the redirect to ssl ?

### ISSUE THREAD

**Issue by hallux4** [ConSol/omd#104]
I handle my ssl certificates with haproxy and let's encrypt.
The haproxy configuration is auto-generated.

I saw this documentation but I am note sure if it can helps.
- https://labs.consol.de/omd/packages/apache/

if I do :
- omd config set APACHE_MODE own

When I access https://FRONTEND-URL,net, it is ok

But for https://FRONTEND-URL,net/demo/ or https://FRONTEND-URL,net/demo/thruk
I get:
This page isn’t working
FRONTEND-URL,net redirected you too many times.

The haproxy backend looks like this
``` bash
backend 12-BACKEND_URL
    mode http
    http-request set-header X-Forwarded-Port %[dst_port]
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server healthy BACKEND_URL:80 check
```

Is it possible to disable the ssl redirect in apache ?

**Comment by sni** [comment]
this has been fixed recently, could you try the current nightly builds to see if its fixed for you as well?

**Comment by hallux4** [comment]
I started the image pulling.
``` bash
docker pull consol/omd-labs-debian:nightly
```
I am working from China and need few hours to pull the image.
So I will try tomorrow or this week end.

Same issue with the Debian repository (around 9 hours ^^).
deb http://labs.consol.de/repo/stable/debian buster main

if I clone the OMD repository and build a .deb file for the nightly version.
Can I just dpkg -i FILENAME.deb onto an existing install ?

**Comment by sni** [comment]
sure, you could build the packages yourself too, but i doubt this is faster. The repository is way larger than the resulting packages.

**Comment by hallux4** [comment]
``` bash
docker run -d -p 8443:443 -p 8080:80 consol/omd-labs-debian:nightly
docker exec -it admiring_napier bash
```

At this point the curl on https give the right output.
```
curl https://172.17.0.2/demo/thruk/cgi-bin/login.cgi?demo/thruk --insecure
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<title>Thruk Monitoring Webinterface</title>
...

OK
```

```
su - demo

OMD[demo@ab252acb602d]:~$ omd version
OMD - Open Monitoring Distribution Version 4.01.20200704-labs-edition, Python version 3.7.3

OMD[demo@ab252acb602d]:~$ omd stop
Removing Crontab...OK
Stopping dedicated Apache for site demo....OK
Stopping naemon....OK
Stopping npcd...OK
Stopping rrdcached...waiting for termination...........OK
OMD[demo@ab252acb602d]:~$ omd config set APACHE_MODE own
OMD[demo@ab252acb602d]:~$ omd start
Preparing tmp directory /omd/sites/demo/tmp...OK
Starting rrdcached...OK
Starting npcd...OK
Starting naemon...OK
Starting dedicated Apache for site demo...OK
Initializing Crontab...OK
```

Is it the right version and/or the right method ?

```
curl http://172.17.0.2/demo/thruk/cgi-bin/login.cgi?demo/thruk
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://172.17.0.2/demo/thruk/cgi-bin/login.cgi?demo/thruk">here</a>.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at 172.17.0.2 Port 80</address>
</body></html>
```

**Comment by sni** [comment]
looks good then. thanks for testing

**Comment by hallux4** [comment]
> 
> 
> looks good then. thanks for testing

I don't understand what is looking good ^^.

The curl on HTTP continue to redirect to HTTPS ?
From a web browser I get a redirection loop.
```
curl http://172.17.0.2/demo/thruk/cgi-bin/login.cgi?demo/thruk
...
<p>The document has moved <a href="https://172.17.0.2/demo/thruk/cgi-bin/login.cgi?demo/thruk">here</a>.</p>
```

**Comment by sni** [comment]
oh sorry, didn't see that. If you change the apache mode from ssl to own, you need to restart the omd site and the system apache. In case of the docker image, the system apache is the main process, so it cannot be restarted. Therefor you need to change to apache own mode during the container provisioning and before the main process starts. It cannot be changed later on.

**Comment by hallux4** [comment]
So yeah the fix is working ^^

Thanks for your help (again).

```
docker stop naughty_wilson; docker start naughty_wilson
```
```
curl http://172.17.0.2/demo/thruk/cgi-bin/login.cgi?demo/thruk
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<title>Thruk Monitoring Webinterface</title>
```
