### ISSUE TITLE
[question] making package 

### ISSUE THREAD

**Issue by beinbliss** [ConSol/omd#11]
hello sni, could you write a procedure to making this package into omd-nc rpm?

**Comment by sni** [comment]
what you mean?

**Comment by beinbliss** [comment]
I mean, what are the steps to make omd-nc git files into RPM package (what are ./configure and 'make' options to make it exactly as it was on ConSol repository for centos releases). Since ConSol repo stopped producing omd-nc packages, but as far as i see this project is not dropped, so thats why i am asking

**Comment by sni** [comment]
./configure
make rpm
However, there should be rpms already.

**Comment by dcec** [comment]
where?
on https://labs.consol.de/repo/testing/rhel6/i386/ there is only omd-1.21.20150311.rhel6.i386.rpm

**Comment by sni** [comment]
oh thats right, minimum centos version which we build right now is centos 7. I didn't get the builds running on centos 6 and lower without major effort.

**Comment by beinbliss** [comment]
does this mean you won't support centos 6 anymore with omd-nc package? what has changed in this package that does not allow it to work on centos 6?

**Comment by sni** [comment]
exactly. The main purpose of this package is to provide a good base for testing naemon and icinga 2, so there hasn't been any support ever. Do not use this in production.

**Comment by beinbliss** [comment]
i do and it works fine.
if it is for testing naemon and icinga2, does this mean naemon,icinga2 will be merged into omd main package in the future ?

**Comment by sni** [comment]
probably not, but we haven't talked about it yet.
