### ISSUE TITLE
bundled check_dns is outdated, not supporting query type

### ISSUE THREAD

**Issue by pbiering** [ConSol/omd#110]
bundled:

```
check_dns v2.2_2020-05-19_53e6f29 (monitoring-plugins 2.2)
..
check_dns -H host [-s server] [-a expected-address] [-A] [-t timeout] [-w warn] [-c crit] [-L]
```

while the one from nagios-plugins-dns has already option for querytype

```
check_dns v2.3.3 (nagios-plugins 2.3.3)
...
check_dns -H host [-s server] [-q type ] [-a expected-address] [-A] [-n] [-t timeout] [-w warn] [-c crit]
```

"Nowadays", one potentially want to check specific querytypes like A, AAAA, CAA, etc...

Please update bundled check_dns, thank you!

**Comment by sni** [comment]
we are bundling https://github.com/monitoring-plugins/monitoring-plugins withing omd. There was a lot going for and back with the nagios-plugins, if the check_dns changes are stable now, i am happy to accept any pull requests for the monitoring-plugins.
Besides that, OMD has a place for user plugins in `~/local/monitoring-plugins/`.
