### ISSUE TITLE
libpangocairo-1.0-0 rrdcached dependency 

### ISSUE THREAD

**Issue by infraweavers** [ConSol/omd#112]
Hello,

Just testing omd nightly, 4.01.20200909-labs-edition on Debian 9. `rrdcached` fails to start as it has a dependency on libpangocairo-1.0-0 (https://packages.debian.org/buster/libpangocairo-1.0-0); installing the package fixes it.

**Comment by sni** [comment]
thanks, should be fine tomorrow
