### ISSUE TITLE
PHP 8.0.0rc1 breaks Histou plugin...

### ISSUE THREAD

**Issue by heinowalther** [ConSol/omd#115]
Hi there
Due to security issues we have been forced to upgrade our PHP to 8.0.0rc1 on out Centos7 box with OMD 3.30-labs-edition installed.
This seems to break the histou plugin that shows the graphs via grafana.
Maybe it breaks even more... I'm not the experienced that I can see inside grafana and see if data is put into the influxdb..

I did try this which confirmed that the new PHP is causing this...
Seems to be related to autoload() procedure... ?

# php -v
PHP 8.0.0rc1 (cli) (built: Sep 29 2020 22:36:51) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
php index.php
PHP Fatal error:  __autoload() is no longer supported, use spl_autoload_register() instead in /opt/omd/versions/3.30-labs-edition/share/histou/histou/bootstrap.php on line 17 

Any quick fix would be great :-)  As we cannot downgrade PHP

/Heino

**Comment by sni** [comment]
So far we only tested omd with php 7. Seems like php 8 is not even released yet.

**Comment by heinowalther** [comment]
As I mentions, PHP7 apparently has some security vulnerabilities, and that's why I was forced to upgrade to 8.0.
I have investigated a bit, and it seems that the way to so the __autoload() is depreciated, even in 7.0..
Seems like spl_autoload_register() should be used instead... I have tried to replace it but with no luck so far...
I think I will investigate if the vulnerabilities may be covered in a version of PHP7, which may be the easier way here :-)

**Comment by sni** [comment]
I'd assume that if there is a security issue in php 7, it will be fixed in php 7 and they won't force you to update to a beta release candidate of php 8.
Anyway, PRs to make histou work with php 8 are welcome.

**Comment by heinowalther** [comment]
You are correct, in fact I was unaware that 8.0 was still in RC... 
So I downgraded to 7.4.11 now, which solved the issue.
I will have a talk with our security officer who lead me on to PHP8 ;-)

Thanks for the quick replies :-)
