### ISSUE TITLE
Missing grafana images on dashboard after update to debian buster

### ISSUE THREAD

**Issue by ibr** [ConSol/omd#116]
Instead of grafana images I had a lot of empty files in /tmp.

After a lot of searching I added a debug log in /opt/omd/versions/3.30-labs-edition/share/thruk/lib/Thruk/Utils.pm
Line 1614: $c->log->error("Call $cmd");

got then:
[2020/10/08 13:46:56][monitor][ERROR] Call /omd/sites/monitor/share/thruk/script/grafana_export.sh "752" "222" "1601293615" "1602157615" "https://127.0.0.1:5000/monitor/grafana/dashboard-solo/script/histou.js?host=moritz&service=CEPH_DF_SSD&theme=light&annotations=true&disablePanelTitle&reduce=1&legend=false&panelId=1" "/tmp/gbAPgHJMlx"

startet grafana_export.sh in the shell and got:

Auto configuration failed
140365648809600:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
140365648809600:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140365648809600:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf

Then I found the solution:
Adding
export OPENSSL_CONF=/etc/ssl/
in .profile

**Comment by ibr** [comment]
https://help.nextcloud.com/t/auto-configuration-failed/35721/2

**Comment by sni** [comment]
strange, any idea why its suddenly required to set `OPENSSL_CONF`? The referenced article is two years old, so its unlikely to be an issue with an specific openssl version.
