### ISSUE TITLE
Grafana image rendering with histou

### ISSUE THREAD

**Issue by MaSc1992** [ConSol/omd#119]
Hello,

The image rendering function in Grafana for Histou dashboards is not working. It runs into a timeout. I've done some research and here are the results:

The local Grafana rendering process uses the local grafana port and address to call the script. For example it calls:
http://127.0.0.1:8003/dashboard-solo/script/histou.js

The url-variable in the histou.js script then fails to get the histou's index.php:

>     var site = window.location.href.match(/(https?:\/\/.*?\/.*?)\/grafana\/.*/);
>     if(site && site.length > 1){
>         url = site[1]+'/histou/';
>     }
>  var configUrl = url+'index.php?host='+host+'&service='+service+'&height='+height+'&legend='+legend+debug+disablePanelTitle+disablePerfdataLookup+specificTemplate+'&annotations='+annotations;

Another problem here is, that the index.php from histou is behind an authentication.

Thank you for providing this project for free and best regards

**Comment by sni** [comment]
i assume this is fixed meanwhile. Image rendering has been migrated to puppeteer with OMD 5.x.
