### ISSUE TITLE
Distro not supported

### ISSUE THREAD

**Issue by 3tan** [ConSol/omd#12]
Trying to install the latest version but its giving me the following error

You are running on CENTOS_1
This distrobution is not supported.  You might succeed anyway.  Good luck.

The cat /etc/redhat-release its calling in the script shows  "CentOS Linux release 7.1.1503"

Any suggestions on making this run?

**Comment by sni** [comment]
how did you solve it?

**Comment by 3tan** [comment]
Sorry I just went back to downloading the rpm from the website :(





Nathan Moody
IS Hardware Technician
Nucor Steel Memphis, Inc.

Phone: (901)-786-5874
Cell: (901)-517-3476
Email: Nathan.Moody@nucor.com<mailto:Nathan.Moody@nucor.com>
