### ISSUE TITLE
livestatus log gets flooded with 60k lines every second

### ISSUE THREAD

**Issue by ghost** [ConSol/omd#120]
There are like 60k lines every second generated in livestatus log file.

Message:
`Sorry, Operator !~~ for lists not implemented.`

Path:
`/omd/sites/<mysite>/var/naemon/livestatus.log`

Version:
`MD - Open Monitoring Distribution Version 4.00-labs-edition, Python version 3.5.3`

**Comment by sni** [comment]
You could create a feature request for the naemon-livestatus project. There is nothing OMD can do about it.
