### ISSUE TITLE
omd backup fails when trying to exclude files

### ISSUE THREAD

**Issue by ghalse** [ConSol/omd#121]
After upgrading to the 4.00 stable package on Ubuntu 20.04.1, attempting to run an `omd backup` on a hot site results in the error:

```
Warning: The site should be stopped for a backup.
ERROR: You can not exclude files from your backup using your Python version 3.8.5. You may need to update.
```

The same occurs when using any of the `--no-*` options to exclude portions of the backup.

This previously worked with 3.30, so I suspect it is something to do with the switch from Python 2 to Python 3.

**Comment by ghalse** [comment]
On investigation, it seems that this _might_ happen because the omd backup command [calls tar.add with an `exclude` parameter](https://github.com/ConSol/omd/blob/a8b28d545c28eb0a88733a0ea6aeed85e0c747fd/packages/omd/omd#L3560). 

According to the documentation, this was [deprecated in Python 2.7](https://docs.python.org/2.7/library/tarfile.html#tarfile.TarFile.add) and [in Python 3.2](https://docs.python.org/3.5/library/tarfile.html#tarfile.TarFile.add) in favour of the `filter` parameter. It appears to have been completely removed as of python 3.7, as there's no longer mention of it in the documentation.

**Comment by datamuc** [comment]
Thank you for the report. 

845ae36 should fix the issue.
