### ISSUE TITLE
OMD support arm64

### ISSUE THREAD

**Issue by Tomasz-Bl** [ConSol/omd#123]
Hello,
is it possible to install OMD Labs on Raspberry Pi 4?
I tried using Ubuntu 20.04, but when I try to install I get the message:

Skipping acquire of configured file 'main / binary-arm64 / Packages' as repository 'http://labs.consol.de/repo/stable/ubuntu focal InRelease' doesn't support architecture 'arm64'

Have a nice day

**Comment by sni** [comment]
there is no official support for arm architecture. From time to time we build or get arm build donations and put them in the repository. But we do not have arm build infrastructure and there are no regular arm builds.
