### ISSUE TITLE
CentOS 7 missing GD dependencies

### ISSUE THREAD

**Issue by manincharge** [ConSol/omd#124]
It appears that on a standard OMD installation after installation on a CENTOS 7 server, that the Trends.cgi won't run because of a missing libgd.so.2 file.   This can be corrected by installing the "gd" (yum install gd)

It appears that the Cent7 build needs to be updated with this package although this is way out of my league to fix.

https://github.com/ConSol/omd/blob/labs/distros/Makefile.CENTOS_7

**Comment by sni** [comment]
thanks, next release will contain the missing dependency.
