### ISSUE TITLE
grafana api access not possible

### ISSUE THREAD

**Issue by peter12222** [ConSol/omd#126]
Hello everybody.

i would like to give an external company access to our grafana dashboards using the grafana api. unfortunately this is currently not possible. When I call up the curl command which I get from grafana, I get the following error message:

```
C:\Users\admin>curl -H "Authorization: Bearer %APIKey%" https://domainname/monitoring/grafana/api/dashboards/home
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://domainname:443/monitoring/thruk/cgi-bin/login.cgi?monitoring/grafana/api/dashboards/home">here</a>.</p>
</body></html>
```

I hope you can help me, many thanks in advance. :)

best regards
Peter

**Comment by peter12222** [comment]
does anyone have any ideas about this problem? we really need a solution.

greetings
Peter

**Comment by sni** [comment]
In OMD everything, including Grafana, uses central authorization via Thruk. You could try to use a Thruk API key instead.

**Comment by peter12222** [comment]
Thanks for the tip.
The connection works perfectly with the Thruk API key. 

Example: 
`curl -H "X-Thruk-Auth-Key: %ThrukAPIKey%" -gk "https://domain.com/%sitename%/grafana/api/dashboards/home" `


Many Thanks
