### ISSUE TITLE
del_active_host_downtimes

### ISSUE THREAD

**Issue by techtuga** [ConSol/omd#129]
Hi, 

Since the update to version 4.20 the external command: del_active_host_downtimes stopped working.
We get an empty response from the api:

curl -ks -d 'comment_data=Stop Downtime' -H 'X-Thruk-Auth-User: #####' -H 'X-Thruk-Auth-Key: #####' https://#####/winnagio/thruk/r/hosts/####/cmd/del_active_host_downtimes
{
   "commands" : "",
   "message" : "Command successfully submitted"
}

Following the link to the naemon command reference, returns a 404 
https://www.naemon.org/documentation/developer/externalcommands/del_active_host_downtimes.html

Can it be that the command was deprecated?

Thanks,
Fred

**Comment by sni** [comment]
the link returns a 404 because its not a real naemon command. Thruk first fetches the matching downtimes and then sends the remove downtime comands for those IDs.
