### ISSUE TITLE
make it possible to restart/reload services with systemd

### ISSUE THREAD

**Issue by lucasteinke** [ConSol/omd#135]
Currently, if you want to reload the naemon config, you can either run the following as root:

```bash
omd reload sitename naemon
```

or as user `sitename`:

```bash
omd reload naemon
```

However, I'd like to programmatically reload or restart certain services (like `naemon`) from systemd because I'm automating this. There's no systemd service file to do this, so I created omd_naemon@.service and put the following in it:

```ini
[Unit]
# %I gets replaced by what you call the service with after the @
Description=Naemon monitoring daemon for OMD site %I

[Service]
Type=oneshot
User=%I
ExecStart=omd start naemon
ExecStop=omd stop naemon
ExecReload=omd reload naemon
```

If I now run `systemctl start omd_naemon@sitename.service`, I get:

```
Jun 17 17:17:35 hostname systemd[1]: Starting Naemon monitoring daemon for OMD site sitename...
Jun 17 17:17:35 hostname omd[2532746]: Starting naemon...OK
Jun 17 17:17:35 hostname omd[2532775]: Stopping naemon....OK
Jun 17 17:17:35 hostname systemd[1]: omd_naemon@sitename.service: Succeeded.
Jun 17 17:17:35 hostname systemd[1]: Finished Naemon monitoring daemon for OMD site sitename.
```

And the naemon service is still not up according to `omd status`.

Same happens if I delete the `User=` line and replace `ExecStart=/usr/bin/omd start %I naemon` and so on.

What am I doing wrong? Is it possible for you to provide service files for systemd so you can use this in services and timers?

**Comment by sni** [comment]
It is not easily (or not at all) possible to integrate OMD into systemd. OMD is designed to
enable the site user to start stop it's own services. And the only thing systemd should do is
autostart the sites which have autostart enabled.

According to your log output, naemon has been stopped. I guess that's the reason why it is not running, but no idea why it stopped immediately after starting.

**Comment by lucasteinke** [comment]
"Starting naemon" and "Stopping naemon" only appears when I do this via systemd (with the provided service file), when I do it via `omd start naemon` it works properly. With [systemd user sessions](https://wiki.archlinux.org/title/systemd/User) it would be possible to do this per user. May I ask why it's not possible to create a single systemd service for every user's OMD services? I didn't quite get how the `omd` CLI tool restarts these services.

**Comment by sni** [comment]
I am not an systemd expert, so this might be the wrong place to ask systemd questions. I have no idea why the service file behaves like this.

The reason why we don't use systemd user sessions yet is that you would have to change everything in omd. This would be a massive change with little benefits. It's not like
you can use systemd in addition to the current init system in OMD, you would have to
use systemd exclusively and this is not feasible.
Also it must be possible to add/change services without root permissions. Not sure if that's
possible at all.

**Comment by sni** [comment]
omd simply runs ./etc/init.d/ init scripts. The order is set by the symlinks in ./etc/rc.d
We thought about systemd for a while but i don't think it is feasible at the moment.
