### ISSUE TITLE
Upgrading from Ubuntu 20.04 to 22.04

### ISSUE THREAD

**Issue by heinowalther** [ConSol/omd#136]
Hi there
I am only asking here, because I was unable to find any forums on OMD.
I have several installations of the Consol Labs version of OMD on Ubuntu 20.04.
It is very tempting to just do a dist-update of Ubuntu to 22.04, hut how will this go with OMD ?
I can see that OMD does has a Reps for 22.04, so my guess would be to do the dits-update, then add the new Reps for OMD and update on top of what is there... but I am not sure if this is that simple?
Has anyone tried this?

**Comment by sni** [comment]
right now, there is no stable omd package for ubuntu 22.04 yet. We still have some issues with the python 3.10 and some other tests are still failing.
When there is a pkg for 22.04, you still need to reinstall OMD. A dist-upgrade does not upgrade OMD. So you either need to reinstall the same OMD release from the 22.04 repo or a new version and do a site update.

**Comment by heinowalther** [comment]
Hello again.  Is there an ETA for 22.04 support?  Are we talking 6 months from now, or do you have any idea when it will reach its way into the nightly versions?

**Comment by sni** [comment]
There are nightly packages available for ubuntu 22.04. Stable release should be ready within the next 2 weeks.

**Comment by heinowalther** [comment]
Hi again...
I have just tried to install this, and it seems to install OK, yet it does not want to start the crontab part of OMD?
Can you confirm that the stable release is available?
I can see that the version I have installed now, it 5.00, I get this as I try to start crontab:
root@:/home/hwa# omd start bgde crontab
Initializing Crontab.../omd/sites/blah/etc/init.d/crontab: line 27: -: command not found
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
ERROR

**Comment by heinowalther** [comment]
Sorry... my bad...  "apt-get -y install cron" did the trick ;-)
(Guess this should be added as a dependency when you install the OMD package?)
I think my Ubuntu is a minimal installation, which is why crontab was not installed by default...

**Comment by sni** [comment]
thanks, i just updated the dependencies.
