### ISSUE TITLE
redhat 8 omd service doesn't start at boot time

### ISSUE THREAD

**Issue by vercetty92360** [ConSol/omd#138]
Hi Team,

I've recently installed omd 4.60 from repo http://labs.consol.de/repo/stable/rhel8/x86_64/ on a redhat 8 machine.

After creating a few sites, I discovered that the sites were not started at boot time, even if they are enabled.

SO I've checked the status of omd service with "systemctl status omd", and with surprise I've got:

Unit omd.service could not be found.

The omd service is not detected on the system.

To have it detected, I need to do: "systemctl daemon-reload", then the above command is able to find the service.

I see that compared to previous 4.40 version, the used file for the service is /omd/versions/default/share/omd/omd.service ( a symlink /usr/lib/systemd/system/omd.service to this file is created):

$ls -l /usr/lib/systemd/system/omd.service
lrwxrwxrwx 1 root root 43 Sep  7 19:43 **/usr/lib/systemd/system/omd.service** -> **/omd/versions/default/share/omd/omd.service**

with 4.40: "systemctl status omd":
.....
Loaded: loaded (/usr/lib/systemd/system/omd.service; enabled; vendor preset: disabled)
....

with 4.60: "systemctl status omd" (when service is detected after damon-reload):
....
Loaded: loaded (/omd/versions/default/share/omd/omd.service; enabled; vendor preset: disabled)
......

so!

I think the service file used on 4.60 version is not detected at boot time, not sure why, but there is clearly a pb... (maybe /omd is mounted to late..)

as a workaround, I have replaced the symlink in /usr with the real file from /omd, and then omd start at boot time

Are you aware of this issue?

thx

**Comment by sni** [comment]
i made some tests and i'd say symlinks are ok. There are a couple of other symlinked service files in there too.
Besides that we had 2 places in the spec file which created the service file. One did a `cp` and the other a `ln`. I changed both to ln now. I also added a daemon-reload call after it.

**Comment by vercetty92360** [comment]
Hi sni,
I'm a little bit confused, you said "symlinks are ok", so you mean there is no pb at all?
do you know why I have this pb?
where did you do this change and it can be reflected in my enviroment? 

Thx a lot in advance

**Comment by sni** [comment]
The start at boot time is broken up to the 4.60 and is fixed in the nightly version. I don't think is has anything to do with your specific setup.

**Comment by vercetty92360** [comment]
Hi sni, I'm not so familiar with the release workflow.
Will the nightly version be available in official RPM repo http://labs.consol.de/repo/stable/rhel8/x86_64/ ?
maybe at the next version? how can we patch the 4.60 installed version?

thx

**Comment by sni** [comment]
The nightly builds are in the testing repository: https://labs.consol.de/repo/testing/
Meanwhile, there is also a 5.00 stable release.

**Comment by vercetty92360** [comment]
Hi Sni, I've updated from 4.60 to 5.00, but still same pb. after a rebot, the "omd" service is not recognized until I do a daemon-reload.

Is there any additionnal action to perform to have this fixed?

here are the package installed:
 $rpm -qa | grep omd
omd-4.60-labs-edition-el8-1.x86_64
omd-5.00-1.noarch
omd-5.00-labs-edition-el8-1.x86_64

thx

**Comment by mittma** [comment]
@vercetty92360 Is it possible, that your /omd (which links to /opt/omd) is not in your root filesystem but has to be mounted (by /etc/fstab or systemd or whatever)?
I have the same problem on SLES15SP4 with OMD 5.10, /opt/omd is an addtional logical volume. After boot, OMD is not started, "systemctl status omd.service" answers with "Unit omd.service could not be found." and "systemd daemon-reload" corrects that.

The problem seems to be a systemd restriction which will not be fixed: https://github.com/systemd/systemd/issues/8307

Possible workarounds: 
- As you already mentioned, copy omd.service from /omd/versions/default/share/omd/ to /usr/lib/systemd/system/ instead of linking it
- Use additional systemd units to daemon-reload after the omd filesystem is mounted and start the omd service explicitely as described here: https://unix.stackexchange.com/questions/291085/systemd-linked-unit-files-on-mounted-disk-fail-to-load

**Comment by sni** [comment]
i think we solved that with https://github.com/ConSol/omd/commit/01ab5f275c7fc288d5380505e5d515dec1ebe7c7 meanwhile.

**Comment by mittma** [comment]
Unfortunately not - you solved the problem with the installer, but when /omd points to a filesystem outside of the root filesystem, you have that problem at every boot. Systemd evaluates its unit files when /omd is not mounted yet - therefore it is unknown. 
You can work around this problem with an additional unit that executes "systemctl daemon-reload" and "systemctl start omd.service" after the filesystem is mounted where omd is located.
In my case (/opt is located in the root filesystem, but /opt/omd is an additional logical volume) it looks like the following:

> #/etc/systemd/system/omd_jumpstart.service
> 
> [Unit]
> Description=restart omd.service stored in /opt/omd
> Requires=opt-omd.mount
> 
> [Service]
> Type=oneshot
> ExecStart=/bin/systemctl daemon-reload
> ExecStartPost=/bin/systemctl start omd.service
> 
> [Install]
> WantedBy=multi-user.target

I have no idea how you could integrate this in your installation - well it's possible, but is it worth the effort?
Check if /opt/omd is a mountpoint - if yes, then create the above mentioned unit file and enable it
Check if /opt is a mountpoint - if yes, then adapt the unit above ("Requires=opt.mount") and enable it

But you could create and enable both units (for /opt/omd and /opt) - they won't hurt anyone, it /omd is located in the root filesystem. But the target audience is really small, perhaps it's enough to mention the possible problem and the necessary workaround.

PS: copying the omd.service unit file to /usr/lib/systemd/system/ will only work till the next OMD installation, then it's a link again ("ln -sfn ..." in your spec file)
