### ISSUE TITLE
Question: Is there a way to see when a 

### ISSUE THREAD

**Issue by vikas027** [ConSol/omd#14]
Hello,
First of all, I must say OMD is awesome. I just have a small question - Is there a way to see **when** a Notification has been enabled or disabled and by **which** user on the check_mk console or any log files (on CentOS) ? Thanks in advance.
Regards.

**Comment by sni** [comment]
no idea, Thruk would log commands to the thruk.log logfile. No idea if and how multisite does that. I'd say you better ask on their mailing list.
