### ISSUE TITLE
Incorrect "Installed-Size" value in Deb packages' control file

### ISSUE THREAD

**Issue by santeri3700** [ConSol/omd#140]
The omd meta packages seem to have an invalid "Installed-Size" value in the control file. This is confirmed to cause problems on Uyuni (and therefore presumably on SUSE Manager too) - related issue [uyuni#6002](https://github.com/uyuni-project/uyuni/issues/6002). 

According to the Debian [deb-control.5](https://manpages.debian.org/testing/dpkg-dev/deb-control.5.en.html) documentation, the "Installed-Size" value should be either populated or left out completely. Currently it seems that the packages available in the ConSol repository have not defined a size.

Example packages:

- https://labs.consol.de/repo/stable/ubuntu/dists/bionic/main/binary-amd64/omd_meta_4.60-labs-edition.deb
- https://labs.consol.de/repo/stable/ubuntu/dists/bionic/main/binary-amd64/omd_labs_meta_4.60.deb
- (Same Ubuntu 20.04, Debian 10 & 11 packages seem to have the same issue)

Example contents of deb package control file (*.deb/control.tar.xz/control):
```
Package: omd-labs-edition
Version: 4.60
Section: main
Priority: optional
Architecture: all
Depends: omd-4.60-labs-edition
Installed-Size:
Maintainer: Sven Nierlein
Description: Open Source Monitoring Distribution
```

**Comment by sni** [comment]
I fixed it for future meta packages. Thanks for the hint. It might take a while (until the next release) till the fix is published.
