### ISSUE TITLE
pnp4nagios --lower-limit and --upper-limit

### ISSUE THREAD

**Issue by dsieborger** [ConSol/omd#143]
I've noticed two issues relating to https://github.com/ConSol/omd/commit/d867708891261f477b6634fb8453e232e3736019

1. The patches seem not to be applied, at least in the OMD Labs 5.00 packages I've installed on Ubuntu 20.04.  From a glance at the Makefile, it seems the files need to be named *.diff instead of *.patch. https://github.com/ConSol/omd/blob/c0b44bd7b43c96133aa7722ca4f3fbcf7b089ad2/packages/pnp4nagios/Makefile#L39
2. The use of `--upper` in default.php also needs to be changed to `--upper-limit` for the same reasons.

Thanks!

**Comment by sni** [comment]
Thanks for noticing. I fixed the filenames with: 5fe961c1bef5f1ca8fe1b51dbf6a129b8e946258
The change is because the rrdtool in OMD 5 has been updated and it does not support --upper/--lower.

**Comment by sni** [comment]
--upper has been fixed with 3d6c1563e4273ba1c13babda069402961d096266
