### ISSUE TITLE
worker.cfg is overwritten when updating from 4.60 to 5.00

### ISSUE THREAD

**Issue by jstark1** [ConSol/omd#145]
it looks like <site>/etc/mod-gearman/worker.cfg will be overwritten with default settings on update.

There is no indication of this in the update log.

```
cat omd-upgrade.log | grep "mod-gearman\|labs"
2022-12-28 17:17:34 - Updating site 'XXX' from version 4.60-labs-edition to 5.00-labs-edition...
 * Installed dir  etc/mod-gearman/worker.cfg.d
Installed default file of version 5.00-labs-edition.
 * Updated        etc/mod-gearman/server.cfg
 * Installed file etc/mod-gearman/worker.cfg.d/custom.cfg
```

**Comment by sni** [comment]
how did you start the update?

**Comment by jstark1** [comment]
omd -f -V 5.00-labs-edition update --conflict=install <site>

**Comment by sni** [comment]
`conflict=install` means exactly that. It installs the new version in case of a conflict. If you start it without force and conflict option, omd would have asked you what to do.

**Comment by jstark1** [comment]
sure, but there could be an output like 

`* Installed file etc/mod-gearman/worker.cfg (forced)`

**Comment by sni** [comment]
i'll see what i can do. Should be doable.

**Comment by sni** [comment]
Output has been improved so it should be more visible now
