### ISSUE TITLE
Tomcat port 8009 is reusing by omd config

### ISSUE THREAD

**Issue by Vani2468** [ConSol/omd#148]
Hi,

We have observed that Tomcat port 8009 is using by omd config resulting below proxy error in performance graphs.

![image](https://user-images.githubusercontent.com/121673444/210831981-04103647-218e-4b6e-84b0-190df5a2f4bd.png)

We tried to change port to 8001 using omd config but it is still using 8009 which is already using by tomcat, it is never using port which we have given.

Kindly advice how to fix this kind of issue.

**Comment by sni** [comment]
Port 8001 is probably already in use by another OMD site. Have you tried setting ex. port to 8010?

**Comment by Vani2468** [comment]
> Have you tried setting ex. port to 8010

Yes, we have already tried to change the port to 8010 and also tried with different port numbers, omd config never uses the port which we have given.

**Comment by sni** [comment]
Do you get any message or errors if you run `omd config set APACHE_TCP_PORT 8010`?

**Comment by Vani2468** [comment]
The actual issue is, It does not take the new port which we are providing using omd config set GRAFANA_TCP_PORT 8007. Everytime apache, grafana and influx db port getting changed when we are trying to change GRAFANA_TCP_PORT.

Before changing port to 8007, please find the below output.

OMD[opt@XXXX]:~$ omd config show
ADMIN_MAIL: XXXX
APACHE_MODE: ssl
APACHE_TCP_ADDR: 127.0.0.1
APACHE_TCP_PORT: 5014
AUTOSTART: on
CORE: naemon
CRONTAB: on
DACRETAIN: off
DEFAULT_GUI: thruk
DOKUWIKI_AUTH: off
DOWNTIMEAPI: off
GEARMAND: on
GEARMAND_PORT: 0.0.0.0:4735
GEARMAN_PROXY: off
GEARMAN_WORKER: on
GRAFANA: on
GRAFANA_TCP_PORT: 8007
INFLUXDB: on
INFLUXDB_HTTP_TCP_PORT: 127.0.0.1:8112
INFLUXDB_META_TCP_PORT: 8113
INFLUXDB_MODE: http
INFLUXDB_RETENTION: 104
LIVESTATUS_TCP: on
LIVESTATUS_TCP_ONLY_FROM: 127.0.0.1
LIVESTATUS_TCP_PORT: 6560
LOKI: off
LOKI_PROMTAIL: off
MOD_GEARMAN: on
MYSQL: off
NAGFLUX: on
NSCA: off
PNP4NAGIOS: off
PROMETHEUS: off
PROMXY: off
SERVICE_AUTORESTART: on
SNMPTRAPD: off
THRUK_COOKIE_AUTH: on
TMPFS: on
VICTORIAMETRICS: off
WEB_ALIAS:
WEB_REDIRECT: off
OMD[opt@XXXX]:~$

============
Trying to change the port to 8007, but it is getting used 8008 even though port 8007 is free. Please find the below output
OMD[opt@XXXX]:~$ omd config set GRAFANA_TCP_PORT 8007
Apache port 5014 is in use. I've choosen 5015 instead.
OMD[opt@XXXX]:~$ omd config show
ADMIN_MAIL: XXXX
APACHE_MODE: ssl
APACHE_TCP_ADDR: 127.0.0.1
APACHE_TCP_PORT: 5015
AUTOSTART: on
CORE: naemon
CRONTAB: on
DACRETAIN: off
DEFAULT_GUI: thruk
DOKUWIKI_AUTH: off
DOWNTIMEAPI: off
GEARMAND: on
GEARMAND_PORT: 0.0.0.0:4735
GEARMAN_PROXY: off
GEARMAN_WORKER: on
GRAFANA: on
GRAFANA_TCP_PORT: 8008
INFLUXDB: on
INFLUXDB_HTTP_TCP_PORT: 127.0.0.1:8114
INFLUXDB_META_TCP_PORT: 8115
INFLUXDB_MODE: http
INFLUXDB_RETENTION: 104
LIVESTATUS_TCP: on
LIVESTATUS_TCP_ONLY_FROM: 127.0.0.1
LIVESTATUS_TCP_PORT: 6560
LOKI: off
LOKI_PROMTAIL: off
MOD_GEARMAN: on
MYSQL: off
NAGFLUX: on
NSCA: off
PNP4NAGIOS: off
PROMETHEUS: off
PROMXY: off
SERVICE_AUTORESTART: on
SNMPTRAPD: off
THRUK_COOKIE_AUTH: on
TMPFS: on
VICTORIAMETRICS: off
WEB_ALIAS:
WEB_REDIRECT: off
OMD[opt@XXXX]:~$

Something might be different on this site from other sites. Kindly advice if this can be fixed.
