### ISSUE TITLE
Default credentials and accessing Grafana/Telegraf

### ISSUE THREAD

**Issue by martinb07** [ConSol/omd#152]
Hi.
I'm new to OMD and installed it on a new SLES 15 SP4. After creating and starting a site I can access Thruk via https://myserver/SITE. So far so good, but I can't find any credentials. Tried several combination omdadmin, omd, site name with no luck.

And another question, how can I access Grafana?

Thanks

Regards
Martin

**Comment by sni** [comment]
you can access grafana with the following url: https://myserver/SITE/grafana
The only user created on omd create is the omdadmin user and the password is printed during omd create. But you can always set a new password from the command line by running: set_admin_password
This will update the password of the "omdadmin" user.

**Comment by martinb07** [comment]
Thanks!!!! You saved my day!!

**Comment by martinb07** [comment]
Grafana and Wiki ist working, but how do I get the influxDB GUI?

Is it possible to get telegraph running?

**Comment by sni** [comment]
I am not aware of a influxdb gui. If there is any, it is not part of OMD. As well as telegraf is not part if OMD. I don't see a reason why it shouldn't work with OMD but it's totally unrelated to OMD.
