### ISSUE TITLE
OMD nightly (omd-5.01.20230206-labs-edition) mod-gearman-worker-go + EPN won't start

### ISSUE THREAD

**Issue by infraweavers** [ConSol/omd#153]
Installed this morning, version `omd-5.01.20230206-labs-edition`

Running mod-gearman-worker-go with `enable_embedded_perl=on` throws this error. Not sure if this is an OMD issue or a `mod_gearman_worker-go` issue, we've disabled it for the timebeing.

In the ~/var/log/gearman/worker.log:
```
[2023-02-07 10:15:05.141][Debug][epn.go:40] starting embedded perl worker
[2023-02-07 10:15:05.141][Error][epn.go:94] epn startup error: failed to start epn worker: fork/exec /omd/sites/default/share/mod_gearman/mod_gearman_p1.pl: exec format error
```

**Comment by sni** [comment]
That's the wrong file. The p1_file= option should either be empty in the worker.cfg or point to bin/mod_gearman_worker_epn.pl
Does a "omd diff etc/mod-gearman/worker.cfg" show changes for the p1 option?

Cheers,
  Sven

**Comment by infraweavers** [comment]
Aha! User error :) We deploy that file in its entirety at the moment so we're misconfiguring it 👍
