### ISSUE TITLE
Ansible on 5.10 throws warnings on push

### ISSUE THREAD

**Issue by infraweavers** [ConSol/omd#154]
![image](https://user-images.githubusercontent.com/36475663/220345882-77051ebc-61ff-4f54-b2d7-460a8a034649.png)

Looks to still be the same problem as: https://github.com/ConSol/omd/issues/141#issue-1400882794

OMD 5.10
Debian 11

**Comment by infraweavers** [comment]
Just to copy from the other thread. I'm going to mark this as solved because installing `python3-distutils` fixes it. It's up to you guys whether you think this should be a dependency on the OMD package (personally I think it probably should).

**Comment by sni** [comment]
We discussed this and will add python3-distutils as dependency for the next release.
