### ISSUE TITLE
Service dependencies in OMD

### ISSUE THREAD

**Issue by heinowalther** [ConSol/omd#159]
Hi there
Not sure if this is the right "forum" but it kinda lands between naemon and thruk...
I would like to create a dependency on specific services to another service..  like I have several checks which use SNMP up again a host, and I would like those to depend on a ping service.. so if the ping service is down, the dependant services does not check or notify...  Pretty basic stuff...  Now I know that this is possible in Nagios XI where you can create a service dependency, yet in the Thruk config GUI you can only create a host dependency for some reason?
You can however add a "parents" option which "kinda" does this, yet not as advanced as a service dependency which is actually referred to in the help message in Thruk... yet you can only create a host dependency...
So am I the only one baffled about this?    Maybe it's possible in naemon yet their documentation isn't great in this regard and it's pretty much a copy/paste from the nagios documentation...  

Any help or explanation is very welcome :-)

/H

**Comment by sni** [comment]
this has been fixed meanwhile and the next release will have both options in the menu. Until then you could simply replace `hostdependency` with `servicedependency` in the url.

**Comment by heinowalther** [comment]
OK, thanks :-)
