### ISSUE TITLE
Pushgateway can't find static files after upgrade to 5.10

### ISSUE THREAD

**Issue by stephki** [ConSol/omd#160]
Hey everyone!

I am facing issues with Pushgateway after my 5.10 upgrade.
After I did not change any configuration to limit access to resources may I ask you for your appreciated help on this? Pushgateway frontend cannot find/load static files which results in the screen below.

![pushgateway1](https://user-images.githubusercontent.com/120179716/225547035-1d21789e-0d19-4d6f-9b84-b1f23e87bc7a.png)
![pushgateway2](https://user-images.githubusercontent.com/120179716/225547063-75191ba4-40a2-4fcb-8670-0e87de0f7ae8.png)

Pushgateway tries to fetch the static files from https://FQDN/SITE/static in my case.

`OMD - Open Monitoring Distribution Version 5.10-labs-edition, Python version 3.10.`

Thank you very much.

**Comment by sni** [comment]
I cannot reproduce this. But i noticed the pushgateway does not write a logfile right now. (fixed in 7d06261c3c8f07a1ab3747d4f557e65fd2ad5b2a)
You could manually apply the change and see if there is anything in the logs.

**Comment by stephki** [comment]
I changed it manually.
At least I can see logs, but nothing related to the issue (just some logs during the starting process).

Looking at the example of jquery, what is the path your installation is loading? Is this path correct?
GET | https://mon.XXX.at/XXXXXX/static/jquery-3.5.1.min.js?v=release-tar-ball

Where should this file be in the file system? Maybe something happened during the upgrade process.

**Comment by sni** [comment]
looks the same here. I don't think the files are in the filesystem, it is a virtual filesystem contained in the pushgateway binary. Could you clear the browser cache?

**Comment by stephki** [comment]
Same with cleared cache :(
Let me try fixing this with a fresh install of 5.10. If that helps I will do a backup restore of my configuration/data. I will come back to you if that helped.

**Comment by stephki** [comment]
I will close this as a fresh installed resolved this. Thank you.
