### ISSUE TITLE
Debian Bookworm repo is missing

### ISSUE THREAD

**Issue by int3ring0** [ConSol/omd#164]
I followed the instructions on https://labs.consol.de/repo/stable/#_debian_bullseye_11_0 for the bookworm release. I got a key for the repo but the repo it self is missing:
deb http://labs.consol.de/repo/stable/debian bookworm main
The debian stuff is dokumented in https://labs.consol.de/repo/stable/#_debian_bullseye_11_0
There are infos how to do it for Debian 12, is it not supported?
Any advice ?

**Comment by jstark1** [comment]
Debian 12 is supported in the next Release, see https://github.com/ConSol-Monitoring/omd/blob/labs/Changelog
In the meantime you can use the testing repo
deb https://labs.consol.de/repo/testing/debian/ bookworm main

**Comment by sni** [comment]
should be there now with the last release.
