### ISSUE TITLE
[Debian 11 Question] omd-5.10 dependencies

### ISSUE THREAD

**Issue by dvnscr** [ConSol/omd#165]
Trying to upgrade omd-5.0 to omd-5.10 on Debian 11 server and getting a bit confused, why OMD became dependent on Chromium web browser and tons of its graphical lib dependencies ? Is it a glitch or is it intended ?

**Comment by sni** [comment]
chromium is required for puppeteer which is used by thruk and grafana to generate reports and pdfs.
So that's intentional.
