### ISSUE TITLE
NSCA Shows error while started.

### ISSUE THREAD

**Issue by ketra** [ConSol/omd#167]
`[root@ovm-nag-01 log]# omd stop amt nsca

Stopping NSCA...OK

[root@ovm-nag-01 log]# ps aux|grep nsca

root     19653  0.0  0.0 112660   972 pts/0    R+   09:59   0:00 grep --color=auto nsca

[root@ovm-nag-01 log]# netstat -anp|grep 5667

[root@ovm-nag-01 log]# omd start amt nsca

Starting NSCA...ERROR

[root@ovm-nag-01 log]# ps aux|grep nsca

amt      19725  0.0  0.0  12964   752 ?        Ss   10:00   0:00 /omd/sites/amt/bin/nsca -c /omd/sites/amt/etc/nsca/nsca.cfg

root     19730  0.0  0.0 112660   968 pts/0    R+   10:00   0:00 grep --color=auto nsca

[root@ovm-nag-01 log]# netstat -anp|grep 5667

tcp6       0      0 :::5667                 :::*                    LISTEN      19725/nsca

[root@ovm-nag-01 log]#`

when removing STORE_PID=1  in the etc/init.d/nsca this error is not show, and pid_file is still created succesfully.

**Comment by sni** [comment]
thanks, should be better with the next release.
