### ISSUE TITLE
grafana doesn't show graph from other OMD instance

### ISSUE THREAD

**Issue by Majestik-Jay** [ConSol/omd#169]
Hello Team,

I use two OMD instances on both servers like below : 
Server A : liv  (omd v 5.00)
Server B : dev  (omd v 5.00)

In Thruk interface I put Server A to show the two backends connections. 
![image](https://github.com/ConSol-Monitoring/omd/assets/140158734/e7d8cb4a-a3fe-4438-a6a4-b7ae7cd0ac54)

all is OK except graph from dev site. All graph from dev are not shown in Grafana : 
Error : 
Not Found

The requested URL /liv/dev/grafana/dashboard/script/histou.js was not found on this server.

So is it possible to show all graph from A and B servers in Thruk interface of A server ? 

Thank's for your help,
Jason.

**Comment by sni** [comment]
it might work if you connect them with a http connection over thruk instead of livestatus. Then the thruk can proxy the requests to that site.

**Comment by Majestik-Jay** [comment]
Ok it works ! 

thank's for your support.

Jason
