### ISSUE TITLE
How to consistently bump the version when compiling from source

### ISSUE THREAD

**Issue by arturmartins** [ConSol/omd#17]
I am trying to upgrade existing OMD 1.20 sites to more update OMD version by compiling from source (issues found in #16).

The build process creates new package with version 1.20, which clashes the version number with the current installed sites. Therefore, I modified the file [Makefile.omd] (https://github.com/ConSol/omd/blob/master/Makefile.omd), set the variable `OMD_VERSION` to '1.26' and the new package was succcessfuly built and installed.

Nevertheless, update a site `omd stop site && omd update site` was not working (unmount tmpfs enters in infinite loop).

The reason was because the [omd] (https://github.com/ConSol/omd/blob/master/packages/omd/omd) script as the version hardcoded:

`grep OMD_VERSION /opt/omd/versions/1.26/bin/omd | head -n 1` 
```
OMD_VERSION = "1.20"
```
Manually changed to "1.26" and the upgrade was successful.

Is there a easier way to make this process simpler, like `make OMD_VERSION='1.26'`? Or I need to manually update both  [Makefile.omd] (https://github.com/ConSol/omd/blob/master/Makefile.omd) and  [omd] (https://github.com/ConSol/omd/blob/master/packages/omd/omd)  before running `./configure`?

**Comment by sni** [comment]
you have to run "make version"

**Comment by arturmartins** [comment]
Thanks :+1: 

It would have been very helpful if this was written in http://omdistro.org/doc/compile_from_source (I would saved few hours).
