### ISSUE TITLE
Monitoring/Restarting/Alerting if OMD is down...

### ISSUE THREAD

**Issue by heinowalther** [ConSol/omd#170]
Hi there
We have several OMD servers running.  We have seen that some of them can end up in a state where influxdb, grafana and naemon stops for whatever reason.
Especially when naemon stops, no one is in charge of alerting... 
I was hoping that someone already thought of this and had a script that could be run as a cron job, and alert if any of the OMD processes were down for more than 5 minutes.. ?
I can see that the OMD process are not standard services so I guess you cannot add the "Restart=on-failure" option ?

Any help you be great :-)

**Comment by lausser** [comment]
There is a plugin lib/nagios/plugins/check_omd.py which can monitor the (enabled) services of an OMD site.
It also can be used as event_handler to restart the failed components. I recommend to setup a separate OMD site on a separate vm (can be a very small one) which runs a check_by_ssh -H prod-omd-server -C lib/nagios/plugins/check_omd.py ....
```
OMD[snclient@HULSE]:~$ omd status
victoriametrics: running
naemon:          running
apache:          running
nagflux:         running
grafana:         running
crontab:         running
------------------------
Overall state:   running
OMD[snclient@HULSE]:~$ lib/nagios/plugins/check_omd.py 
OK: OMD site 'snclient' services are running.
OMD[snclient@HULSE]:~$ omd stop crontab
Stopping crontab...OK
OMD[snclient@HULSE]:~$ omd status
victoriametrics: running
naemon:          running
apache:          running
nagflux:         running
grafana:         running
crontab:         stopped
------------------------
Overall state:   partially running
OMD[snclient@HULSE]:~$ lib/nagios/plugins/check_omd.py 
CRITICAL: OMD site 'snclient' has failed service(s): 'crontab'
OMD[snclient@HULSE]:~$ lib/nagios/plugins/check_omd.py --heal
Stopping crontab...already empty...OK
Starting crontab...OK
WARNING: Restarted 1 service(s) on site 'snclient': 'crontab'
OMD[snclient@HULSE]:~$ lib/nagios/plugins/check_omd.py 
OK: OMD site 'snclient' services are running.
OMD[snclient@HULSE]:~$ 
```

**Comment by heinowalther** [comment]
Thank you for the quick reply.  I will implement this check from our central monitoring server 👍

**Comment by heinowalther** [comment]
Just a note... seems like the script is somewhat broken... some of our older installations seems to use an older version of the script where it uses "python" and not "python3" which leads the script to fail...
Another thing is that it uses the user executing the script to deduce the site name, so it works fine as "site-name-user", but not if you run is as say root, or another user...  there does not seem to be an option to specify the site name?  But should be fairly simple to modify the script I guess...
