### ISSUE TITLE
/opt/omd/versions/5.20-labs-edition/lib/node_modules/@puppeteer/browsers/lib/cjs/launch.js:259

### ISSUE THREAD

**Issue by Kyetech-IT-Manager** [ConSol/omd#171]
After upgrading to 5.2.0 (from 5.1.0)
 on openSUSE 15.5

Reporting
 - either run an old report or create a new report - receive the error below
 - running Win 10 with Chrome Version 116.0.5845.97 (Official Build) (64-bit)
 - browsing to the OMD server

--
 /opt/omd/versions/5.20-labs-edition/lib/node_modules/@puppeteer/browsers/lib/cjs/launch.js:259
reject(new Error([
^

Error: Failed to launch the browser process!
./lib/node_modules/puppeteer/.local-chromium/chrome/linux-114.0.5735.133/chrome-linux64/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://pptr.dev/troubleshooting

at Interface.onClose (/opt/omd/versions/5.20-labs-edition/lib/node_modules/@puppeteer/browsers/lib/cjs/launch.js:259:24)
at Interface.emit (node:events:525:35)
at Interface.close (node:readline:590:8)
at Socket.onend (node:readline:280:10)
at Socket.emit (node:events:525:35)
at endReadableNT (node:internal/streams/readable:1358:12)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
mv: cannot stat '/omd/sites/Kyetech/var/thruk/reports/4.dat.pdf.pdf': No such file or directory

---

missing nodejs ??

zypper in nodejs

kye-mon01:~ # rpm -qa | grep node
nodejs18-18.17.1-150400.9.12.1.x86_64
nodejs-common-5.1-150500.1.1.x86_64

kye-mon01:~ # node -v
v18.17.1
kye-mon01:~ # npm -v
9.6.7
kye-mon01:~ # npx -v
9.6.7

still the same error

omd stop, restart apache2, omd start
 - same error

reboot
 - same error

**Comment by sni** [comment]
the real issue is here:
> ./lib/node_modules/puppeteer/.local-chromium/chrome/linux-114.0.5735.133/chrome-linux64/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

this simply means we forgot a dependency required for chrome.
running `ldd ./lib/node_modules/puppeteer/.local-chromium/chrome/linux-114.0.5735.133/chrome-linux64/chrome` should not return any missing libraries.
If there are some, you can run zypper to find the missing packages. There might be more
packages missing. We then can add those package names to the rpm dependency list.

But it also be the case that the rpm is not compatible with opensuse 15.5. We only build packages for 15.4 right now.

**Comment by sni** [comment]
i added some more dependencies in e113628a5cb0f5f40bf3b582b5bf6e61186c9d88, you could manually install them and see if the reports work again.

**Comment by Kyetech-IT-Manager** [comment]
Thanks.  Installed them missing libs.

---
zypper in libatk-1_0-0 libatspi0 libcups2  libdrm2  libgio-2_0-0  libxcb1    libXcomposite1 libXdamage1  libXrandr2  libXrender1 

'libgio-2_0-0' is already installed.
'libXrender1' is already installed.
'libcups2' is already installed.
'libdrm2' is already installed.
'libxcb1' is already installed.

The following 7 NEW packages are going to be installed:
  atk-lang libXcomposite1 libXdamage1 libXi6 libXrandr2 libatk-1_0-0 libatspi0
---

So looks like some were already installed

***

now getting 

Error: Failed to launch the browser process!
./lib/node_modules/puppeteer/.local-chromium/chrome/linux-114.0.5735.133/chrome-linux64/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shar

So installed from SLE_15_SP2
zypper addrepo https://download.opensuse.org/repositories/GNOME:STABLE:3.34/SLE_15_SP2/GNOME:STABLE:3.34.repo
zypper refresh
zypper install libatk-bridge-2_0-0

zypper install libatk-bridge-2_0-0
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 4 NEW packages are going to be installed:
  at-spi2-core at-spi2-core-lang libXtst6 libatk-bridge-2_0-0

---
Next error

libxkbcommon

zypper addrepo https://download.opensuse.org/repositories/home:Dead_Mozay:telegram/15.5/home:Dead_Mozay:telegram.repo
zypper refresh
zypper install libxkbcommon0

kye-mon01:~ # zypper install libxkbcommon0
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following recommended package was automatically selected:
  xkeyboard-config-lang

The following 3 NEW packages are going to be installed:
  libxkbcommon0 xkeyboard-config xkeyboard-config-lang

---

Now can run the reports

That was fun.

**Comment by sni** [comment]
glad it works now. Still strange, our opensuse 15.4 build server does not have any external repositories and was able to install all required dependencies:

```
#>zypper repos -E -u
Repository priorities are without effect. All enabled repositories share the same priority.

# | Alias                             | Name                                                         | Enabled | GPG Check | Refresh | URI
--+-----------------------------------+--------------------------------------------------------------+---------+-----------+---------+-------------------------------------------------------------------
1 | openSUSE-Leap-15.4-Non-Oss        | openSUSE-Leap-15.4-Non-Oss                                   | Yes     | (r ) Yes  | No      | https://download.opensuse.org/distribution/leap/15.4/repo/non-oss/
2 | openSUSE-Leap-15.4-Oss            | openSUSE-Leap-15.4-Oss                                       | Yes     | (r ) Yes  | No      | https://download.opensuse.org/distribution/leap/15.4/repo/oss/
3 | openSUSE-Leap-15.4-Update         | openSUSE-Leap-15.4-Update                                    | Yes     | (r ) Yes  | No      | https://download.opensuse.org/update/leap/15.4/oss/
4 | openSUSE-Leap-15.4-Update-Non-Oss | openSUSE-Leap-15.4-Update-Non-Oss                            | Yes     | (r ) Yes  | No      | https://download.opensuse.org/update/leap/15.4/non-oss/
6 | repo-backports-update             | Update repository of openSUSE Backports                      | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/update/leap/15.4/backports/
8 | repo-sle-update                   | Update repository with updates from SUSE Linux Enterprise 15 | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/update/leap/15.4/sle/

```
