### ISSUE TITLE
5.30: EL9 RPM has huge dependency tree in difference to EL8

### ISSUE THREAD

**Issue by pbiering** [ConSol/omd#177]
While testing update from 5.20 to 5.30 it turns out that on EL9 the RPM dependency tree is much longer and resulting in unexpected installation of packages like

- chromium
- flatpak-session-helper
- xvidcore
.... (194 package here in sum)

Was this intended?

**Comment by sni** [comment]
that's intentional. In comparisson, el8 has a bigger rpm size because it contains chromium while rocky 9 uses the systems chromium.

**Comment by pbiering** [comment]
Just note that the new dependency tree activates `avahi-daemon` which is usually not required on servers, following commands will at least permanently disable it:

```
systemctl disable --now avahi-daemon.service
systemctl disable --now avahi-daemon.socket
```
