### ISSUE TITLE
Fresh installed OMD labs stable: check_mk issues

### ISSUE THREAD

**Issue by arturmartins** [ConSol/omd#18]
List of services started:

```
omd start
Starting influxdb..............OK
Starting Grafana...OK
Starting Nagflux...OK
Starting naemon...OK
Starting dedicated Apache for site testing...OK
Initializing Crontab...OK
```
#### Issue: Missing column in DB

<img width="929" alt="screen shot 2015-12-02 at 2 48 40 a m" src="https://cloud.githubusercontent.com/assets/101411/11521006/3ea4e396-98a0-11e5-8d59-2910a9dd6868.png">
<img width="838" alt="screen shot 2015-12-02 at 2 47 14 a m" src="https://cloud.githubusercontent.com/assets/101411/11521007/3ea84ab8-98a0-11e5-98d2-d7f2c91be66f.png">
Unable to visualize host/services/hostgroups/etc. Found out that this is a duplicate of #4. This is a fresh server with fresh installed OMD Version 2.10-labs-edition.
#### Issue: Missing directories for naemon

<img width="681" alt="screen shot 2015-12-02 at 1 52 01 a m" src="https://cloud.githubusercontent.com/assets/101411/11521008/3eaf70c2-98a0-11e5-9a31-44089838b1c8.png">
This makes impossible to create hosts.

Workaround:

```
mkdir -p /usr/local/var/log/naemon/
mkdir -p /usr/local/var/spool/checkresults
chmod 777 -R /usr/local/var
```

**Comment by Griesbacher** [comment]
Both problems lies between neamon and multisite/mk, so maybe their issue trackers are the right place for such issues.

**Comment by marblerun** [comment]
The system actually creates a file .../site/tmp/naemon/naemon.cfg, which clearly states on line 2 that the file has been created by OMD. So something in the many config files then referenced below that must be incorrect.

That would also account for it not finding the logfile, as 14 naemon cfg files are referenced to the correct site specific location.

**Comment by smarmie** [comment]
Hi,
I'm having the same issue with a fresh install of omd-2.20-labs-edition=0.ubuntu16.04
However, the workaround is not working.
Thanks.

**Comment by sni** [comment]
You could try the nightly builds, cmk has been updated meanwhile. Or try setting the core to nagios.

**Comment by lgwapnitsky** [comment]
Still occurring as of latest stable version

**Comment by heinzelrumpel** [comment]
I actually cannot beliefe, that this error has not been fixed and that that there is no fix resp. workarround posted somewhere. Sorry, but what makes it so difficult to include those columns into livestatus installation?

**Comment by lausser** [comment]
The easiest and quickest way to get this done is to fix it and send us a pull request.
The workaround is not to use check_mk.

**Comment by davidedg** [comment]
I really think this is deliberate - see also comment https://github.com/ConSol/omd/issues/4#issuecomment-323074525 - what should you use, if not cmk, for configuring the core, in omd ?
Been trying omd labs for over 2 years, always found it to be utterly broken.

**Comment by lausser** [comment]
We (at ConSol) do not use check_mk, we do not recommend using check_mk. For everybody who thinks that Nagios is not usable without check_mk: 
Go to [omdistro.org](http://omdistro.org) and turn to the left, there is an OMD maintained by MK himself. If it is free or open source, i don't know.
OMD Labs Edition on the other side, is 100% free and open source. If it would be broken, then it would not be the preferred monitoring tool for several large-scale enterprises. This allows us to make the money necessary to maintain OMD.
Configuration is done by manually editing config files, mostly using templates and hostgroups. Companies which have some sort of CMDB (and most of them have one, instead of letting check_mk doing the inventory of their IT zoo) use [Coshsh](https://github.com/lausser/coshsh)

**Comment by davidedg** [comment]
Gerhard, thank you for making this clearer.
What I meant by deliberate is just this: omd-lab _do_ contains Check_MK (often older versions), as in RAW edition, but not only it does not work, you are confirming that there's no will to make it work.
I think this might be misleading - why not leave out check_mk from the package if it's broken in the first place?
