### ISSUE TITLE
thruk filter "Plugin Output" is not affecting numbers in  "Service Status Totals"

### ISSUE THREAD

**Issue by pbiering** [ConSol/omd#180]
In service-detail view I can filter for service groups and others which affects numbers in "Service Status Totals"

But filter for "Plugin Output" is not affecting the numbers, only reducing the amount of listed services according e.g. to the match of a given regular expression.

Is this a bug since long time or a missing feature or impossible to implement?

**Comment by sni** [comment]
not really an omd issue, please open thruk related issues in the thruk repository next time.
Anyway, i checked back till version 2.00 and it has always been like this. But yes, i'd
would consider this wrong too, so i fixed it in: https://github.com/sni/Thruk/commit/8fce658cdb317d56cb275487ad946bdb38928daf
