### ISSUE TITLE
5.30 on EL9: livestatus / xinetd hang during start if started by systemd

### ISSUE THREAD

**Issue by pbiering** [ConSol/omd#182]
Enabled livestatus in 5.30 on EL9: xinetd is working fine on manual start of "omd" but not via "systemd".

Finally it turned out, that it works by either

- remove/disable line in systemd unit file: `#LimitNOFILE=infinity`
- override value with a numeric one, e.g. `LimitNOFILE=10240`

Very strange, not seen on EL8 - EL9 had latest updates.

Symtom was that script started `xinetd`, but this hang before creating its PID file.

**Comment by sni** [comment]
sounds like a similar issue as in https://github.com/ConSol-Monitoring/omd/commit/4ccf937f9068c0b9197b0d633dfcb618f94a923b

in that case, the npcd tried to brute force close all filehandles on fork from 0 to max-open-files. And infinity is a pretty large number :-)
Maybe xinetd is doing something similar

**Comment by sni** [comment]
fixed in daaba3e32a31506a6a8a766b0b9f462f2821f632
