### ISSUE TITLE
No data in Reports -> Event log , trends, notifications

### ISSUE THREAD

**Issue by hamdyaea** [ConSol/omd#183]
Hi,

I have the version omd 5.30 on a Ubuntu 22.04.

Everything is working but I see no data in the web gui on Reports -> Event log. I have the same problems on Trends and Notifications.

**Comment by sni** [comment]
Which core do you use?

**Comment by hamdyaea** [comment]
Here's the output of my config : 

root@monitoring:~# omd config kms_live show
ADMIN_MAIL: info@md.com
APACHE_MODE: ssl
APACHE_TCP_ADDR: 127.0.0.1
APACHE_TCP_PORT: 5000
AUTOSTART: on
CORE: naemon
CRONTAB: on
DACRETAIN: off
DEFAULT_GUI: thruk
DOKUWIKI_AUTH: off
DOWNTIMEAPI: off
GRAFANA: off
INFLUXDB: off
LIVESTATUS_TCP: off
LOKI: off
LOKI_PROMTAIL: off
MOD_GEARMAN: off
MYSQL: off
NAGFLUX: off
NSCA: off
PNP4NAGIOS: on
PROMETHEUS: off
PROMLENS: off
PROMXY: off
SERVICE_AUTORESTART: off
SNMPTRAPD: off
THRUK_COOKIE_AUTH: off
TMPFS: on
VICTORIAMETRICS: off
WEB_ALIAS:
WEB_REDIRECT: off

root@monitoring:~# ps aux | grep omd | grep -E 'nagios|naemon|icinga'
live    1433  0.0  0.0 150388   536 ?        S    06:00   0:00 /omd/sites/live/bin/npcd -d -f /omd/sites/live/etc/pnp4nagios/npcd.cfg
live    1668  2.4  0.1 203200 36116 ?        Ss   06:00   2:33 /omd/sites/live/bin/naemon -ud /omd/sites/live/tmp/naemon/naemon.cfg
live    1839  0.0  0.0  69624 21768 ?        S    06:00   0:00 /omd/sites/live/bin/naemon -ud /omd/sites/live/tmp/naemon/naemon.cfg
live   75290  0.1  0.0   9048  4020 ?        S    06:05   0:09 /omd/sites/live/bin/naemon --worker /omd/sites/live/tmp/run/naemon.qh

I have two servers with Ubuntu 22.04 and they are a copy of one another. On this one I can't see nothing under Reports in the Thruk GUI. But in the other one everything works. 

This is a maybe a permission or owner issue ? But I don't know which files I have to check.

**Comment by sni** [comment]
how are you doing the copy? Is this some active/passive failover thing?
You can check if there are logs on that machine. Is there anything in var/naemon?

**Comment by hamdyaea** [comment]
I do a rsync of the configs files on another omd server BUT this one is the main server. Nothing is copied into it. 
The Event logs and everything under reports is always empty. 
![Capture](https://github.com/ConSol-Monitoring/omd/assets/25694730/29f42f51-f5fe-4f95-8de6-7a0f9fcfeeaa)

**Comment by hamdyaea** [comment]
Here's the content of /var/naemon : 
drwxrwxr-x  2 live live  12K avr 12 11:00 archive
-rw-r--r--  1 live input    597K avr 17 13:28 debug.log
-rw-r--r--  1 live input    977K avr 17 13:28 debug.log.old
-rw-r-----  1 live live  24K avr 17 11:27 livestatus.log
-rw-r-----  1 live live  148 jui 12  2021 livestatus.log.1
-rw-r-----  1 live live   88 jun 17  2021 livestatus.log.2.gz
-rw-r-----  1 live live   88 mai 28  2021 livestatus.log.3.gz
-rw-r-----  1 live live  193 mai 19  2021 livestatus.log.4.gz
-rw-r-----  1 live live  102 mai  4  2021 livestatus.log.5.gz
-rw-r-----  1 live live   88 avr 23  2021 livestatus.log.6.gz
-rw-r-----  1 live live   88 avr 19  2021 livestatus.log.7.gz
-rw-rw-r--  1 live live 221M avr 17 13:28 naemon.log
-rw-rwxr--  1 live live 991K nov  8  2019 nagios.log
-rw-rw-r--  1 live input    8.3M avr 17 13:25 objects.precache
-rw-------  1 live input    9.9M avr 17 12:05 retention.dat

**Comment by sni** [comment]
do you sync the logs as well, including the `archive` folder? You also might have to reload naemon after syncing the logfiles, so livestatus will look for new logfiles again.

**Comment by hamdyaea** [comment]
How can I reload naemon only ?

**Comment by sni** [comment]
in OMD? simply run `omd reload naemon`

**Comment by hamdyaea** [comment]
I have removed every cron jobs on the logs.
Now I have done an omd reload naemon but I still can't see any logs.
But I have to let it run a few days to see if they comes.

**Comment by hamdyaea** [comment]
The naemon log file is 225 Mb but I see nothing in the Nagios OMD Labs GUI under Reports/Event Logs. Can you tell me if I have to look at other files then that ? /opt/omd/sites/kms_live/var/naemon/naemon.log ?

-rw-rw-r-- 1 live live 225M avr 18 12:51 /opt/omd/sites/live/var/naemon/naemon.log

**Comment by hamdyaea** [comment]
So I have let run the server alone without sync or nothing, I have do a omd reload, omd reload naemon. But It's still the same. I don't find why there's nothing in /Reports/ Events logs and trends (Trends is always 100 Undetermined for all hosts/services).

**Comment by sni** [comment]
Thruk fetches the logs via livestatus, so you have to make sure livestatus provides those logs.
You can test livestatus logs with the command:
`echo -e "GET log\nFilter: time > 0\nLimit: 1\n" | lq`
The livestatus config is in:
`etc/naemon/naemon.d/livestatus.cfg`
You can add a debug=3 there and see if var/naemon/livestatus.log contains any hints.

**Comment by hamdyaea** [comment]
I have found the issue. 

there was too mane entries in livestatus.log and there was an alert in the logs that the logs of Naemon are now ignored.

I have delete the logs and recreated them empty with the touch commands. Then I have do an omd reload and it's working.
