### ISSUE TITLE
SNClient gui is not loaded ?

### ISSUE THREAD

**Issue by esdras007** [ConSol/omd#189]
Hello,
Something very strang is happening here. I'm trying to use snclient to set up some config and check but the gui is not loaded as the documentation said https://nsclient.org/docs/web/, on my side it's displaying "snclient working...." what does it mean ?
Can someone tell me how to access the web ui ? is there a property to enable to have it ?
Please help.

Thanks

**Comment by sni** [comment]
snclient does not have a web ui. Right now there are no plans to add something like this.
Only the REST API to run the checks in implemented.

**Comment by esdras007** [comment]
Hello, 
Thanks for your feedback, so which suitable tool can I use as config manager ? can NagiosQL can be used ?

**Comment by sni** [comment]
That might work, in the end it's just simple naemon config on the other side.
You also might want to have a look at the "agents" plugin for thruk which
is a config manager for snclient, see:
- https://thruk.org/whatsnew/v3.10.html#_agents-plugin
- https://github.com/sni/Thruk/tree/master/plugins/plugins-available/agents

The plugin is available in the OMD nightly builds already.

**Comment by esdras007** [comment]
Ok thanks, I have a proxy on my server, can't run git clone, is there a way to download the zip instead of git clone ?

**Comment by sni** [comment]
you don't need to clone anything, the latest omd nightly has this plugin already. Just enable it with `thruk plugin enable agents`

**Comment by esdras007** [comment]
I installed the lastest stable version.
Can you share the url to download the nightly lastest built rpm rel9 packages ?

**Comment by esdras007** [comment]
I finally got your point, I found it and activated with the symbolic link
