### ISSUE TITLE
Command omd disable clears crontab for root.

### ISSUE THREAD

**Issue by ketra** [ConSol/omd#191]
When running the command omd disable, the crontab for the root user is cleared.

When running stop (this is correct)
![image](https://github.com/user-attachments/assets/18f3b6cd-cc2d-48c4-b170-b3133c7eb2d5)
When running disable
![image](https://github.com/user-attachments/assets/5cbaabef-c285-4594-b69e-b3864b2b870f)

The issue is within switching context to the siteuser for a stop action, this switch does not take place for the disable action.

**Comment by sni** [comment]
thanks for reporting this, should be fine with the latest nightly build.
