### ISSUE TITLE
max_check_attempts is 1 and still goes to SOFT state on frist try

### ISSUE THREAD

**Issue by Tentoaloe** [ConSol/omd#193]
Hello,

I just noticed that if I set the max_check_attempts to 1 and the server goes DOWN, it still goes only to  SOFT state, but it should go to HARD one.

I have found a bug for Nagios, maybe it is the same for OMD/Naemon?
https://github.com/NagiosEnterprises/nagioscore/issues/23

I am using OMD 5.30 with Naemon.

**Comment by sni** [comment]
yes, there is a similar issue for naemon https://github.com/naemon/naemon-core/issues/473

**Comment by Tentoaloe** [comment]
and is there any workaround or solution for this issue?

**Comment by Tentoaloe** [comment]
I have seen your comment on the other issue you have linked.
When I will be able to use that fix?

**Comment by sni** [comment]
As soon as the pull request got reviewed i will merge it into naemon master. Then, when we think it's time for a naemon release we usually also update the naemon version in OMD.

But we can also pull in some patches earlier which i did now with: b9ef14287d028c6318260902cf70fd2a8680e01f
So it will be part of tomorrows nightly build already.
