### ISSUE TITLE
Nagios OMD webpage isNagios OMD site works but appearance is completely destroyed after updating from 5.30 to 5.40

### ISSUE THREAD

**Issue by hamdyaea** [ConSol/omd#194]
I am using Nagios OMD version 5.30.

Creating temporary filesystem /omd/sites/live/tmp...OK
Starting rrdcached...OK
Starting npcd...OK
Starting naemon...OK
Starting apache...OK
Starting crontab...OK

I try to upgrade to version 5.40.

Nagios OMD is working after the upgrade but the appearant of the web pages are completely destroyed. I only have white pages with raw text.

I am on Ubuntu 22.04

**Comment by sni** [comment]
please update to the latest nightly, this has been resolved already.
