### ISSUE TITLE
500 internal server error after login

### ISSUE THREAD

**Issue by celson** [ConSol/omd#20]
I installed the version of omd 2.10 and after creating a site and start it occurs the 500 error message .

**Comment by rockaut** [comment]
you may switch the core to nagios for a workaround.
has something todo with the config files not switching.

**Comment by sni** [comment]
Check the logfiles. Without any error message, nobody will be able to help.

**Comment by celson** [comment]
Sorry about that. I fixed this problem with "cp -p /usr/lib64/python2.7/hashlib.py /opt/omd/versions/2.10-labs-edition/lib/python/hashlib.py". After copy hashlib the OMD started. Thanks.

**Comment by sni** [comment]
ok, this should be fixed already with the next release.
