### ISSUE TITLE
login page broken with Thruk cookie auth

### ISSUE THREAD

**Issue by jstark1** [ConSol/omd#201]
CSS styles and JS in the login form should be allowed.

![grafik](https://github.com/user-attachments/assets/3be00e85-0694-431f-bec1-56f52a15adc6)

I am using the omd-labs-debian:nightly container

**Comment by sni** [comment]
thanks for reporting this, i thought this issue was fixed already. I'll have a look at the container images.

**Comment by sni** [comment]
i cannot reproduce this. Can you double check the etc/apache/conf.d/thruk_cookie_auth.conf

Line 29 should look like this:
`RewriteRule ^/(.*)$                  /auth:%1/%{REMOTE_ADDR}~~%{HTTP:Authorization}~~%{HTTP?....`
the important part is the `auth:` prefix.

Or check with `omd diff etc/thruk/apache_cookie_auth.conf` if there are local adjustments.

**Comment by jstark1** [comment]
Ah, there's the problem. Is there an easy way to update unchanged files from the Skel directory in the container, like "omd update" does for "normal" installations?

**Comment by sni** [comment]
no, the container are intendend for one-time tests only and should be removed and recreated afterwards. There is no update path for the container images.
