### ISSUE TITLE
omd-labs-edition non-standard meta-data

### ISSUE THREAD

**Issue by bish0polis** [ConSol/omd#202]
RPMs generated at `https://labs.consol.de/repo/stable/rhel9/x86_64` show broken metadata:

    Name        : omd-5.40-labs-edition
    Version     : el9
    Release     : 1
    Architecture: x86_64
    
    Provides:
    
    omd
    omd-5.40-labs-edition = el9-1
    omd-5.40-labs-edition(x86-64) = el9-1

This naming does not conform with the standard.  Why is the versioning jammed into the `%{name}`?  Why is the `el9` encoded in the versioning at all?

Why is it not

    Name        : omd-5.40-labs-edition
    Version     : 5.40
    Release     : 1
    Architecture: x86_64
    
    Provides:
    
    omd-5.40-labs-edition = 5.40    # implicit
    omd-labs-edition = 5.40         # implicit
    omd = 5.40                      # custom

or if we follow lazy RH method and include the distro in the release but not the version:

    Name        : omd-5.40-labs-edition
    Version     : 5.40
    Release     : 1.el9
    Architecture: x86_64
    
    Provides:
    
    omd-5.40-labs-edition = 5.40-1.el9    # implicit
    omd-labs-edition = 5.40-1.el9         # implicit
    omd = 5.40-1.el9                      # custom

That last version is a little gauche, but they've shed a lot of builders over the years so we're just happy they're still trying to participate past el6.

It's a little janky reinventing `alternatives`, but that's something RH does too, and I think they invented it.

**Comment by sni** [comment]
The idea is simple. Having the version as part of the name makes each rpm technically its own product. This is required to have multiple OMD versions installed in parallel.
So you can have multiple sites on one host and each site can use a different version.
And since you need to change the version of a site with `omd update` we do not rely on
all the different package managers and have a well working way of handling updates which
is consistent over all different supported linux systems.
This also allows for example creating a `omd backup` on rhel7 and install this with `omd restore` on a debian 12.
Hope this helps.

**Comment by bish0polis** [comment]
> The idea is simple. Having the version as part of the name makes each rpm technically its own product. This is required to have multiple OMD versions installed in parallel.

You write as if you're suggesting *omitting* the proper meta-data is a requirement, and that's just not the case. You're talking about what we've called "alt"-packages for decades: php533, gcc12, python3 from either python35, python36, python39, etc.  This seems like exactly what you need, and the framework's been installed, tested and refined for as long as we've had alt-packages.

```
# yum search gcc-toolset*binutils
gcc-toolset-12-binutils.x86_64 : A GNU collection of binary utilities
gcc-toolset-13-binutils.x86_64 : A GNU collection of binary utilities

# yum info gcc-toolset-12-gcc.x86_64
Name         : gcc-toolset-12-gcc
Version      : 12.2.1
Release      : 7.7.el9_4
```

Reinventing `alternatives`, too, seems like a lot of effort just to avoid the centralized, canonical method of doing that very thing.   It actually 20 years old, now, having been rewritten from some debian scripts, I think, back in 2004, except in sexy python instead of compatible bash or ephemeral perl.  For hosts with `alternatives` - basically everything with symlinks now - it's a very capable tool that eliminates orphaned configs.

Proper versioning will avoid the need for massive omnibus packages, as well, but that's a whole other discussion.  At least valid metadata will adhere to standards.

I'm off to find a cmk.
