### ISSUE TITLE
Prblems after update httpd on Rocky Linux 8 and RHEL 8

### ISSUE THREAD

**Issue by polorod** [ConSol/omd#203]
Get 403 errror when cgi-bin with arguments

ex. 
https://monitoreo-seg.crevi-mx.com/SEG/thruk/cgi-bin/status.cgi **<-- Works welll**

https://monitoreo-seg.crevi-mx.com/SEG/thruk/cgi-bin/status.cgi?style=hostdetail  **<-- Don't WORK**

It was working, but update to httpd-2.4.37-65.module+el8.10.0+1842+4a9649e8.2

SO Rocky linux 8.10
OMD 5.40
http 2.4.37-65.module+el8.10.0+1842+4a9649e8.2

All Rock Linux updated

**Comment by sni** [comment]
It is fixed in the latest nighty version already. So you could use that one.
