### ISSUE TITLE
Thruk URL not working after httpd upgrade

### ISSUE THREAD

**Issue by Vani2468** [ConSol/omd#204]
We have observed that on RHEL7 OS, after recent patching on OS the httpd package got updated to httpd-2.4.6-99.el7_9.2 from httpd-2.4.6-99.el7_9.1, after that the thruk URL not working and getting below error

**You don't have permission to access /omv/thruk/cgi-bin/main.cgi on this server.**

After downgrading the httpd version to httpd-2.4.6-99.el7_9.1, the Thruk URL started working.

Kindly suggest how to fix the issue with out downgrading the httpd package.

**Comment by sni** [comment]
The solution is to update to a nightly version or add the `UnsafeAllow3F` manually until the next stable release.

- #203 
- #201
- #192
