### ISSUE TITLE
Migrating OMD 5.10 from RHEL 7 to RHEL 9

### ISSUE THREAD

**Issue by Vani2468** [ConSol/omd#205]
We are planning to migrate OMD 5.10 from RHEL 7 to RHEL 9. We have created a new RHEL 9 server, we would like to migrate OMD 5.10 to RHEL 9 to RHEL 7.

Can you advice some best practices on how to migrate OMD 5.10 from RHEL 7 to RHEL 9.

**Comment by lausser** [comment]
You mean a detailed step-by-step instruction document?

**Comment by Vani2468** [comment]
Brief instructions also fine, not in detailed one.

**Comment by lausser** [comment]
Well f you have one OMD 5.10 on RHEL 7, which has a site XY and one OMD 5.10 on RHEL 7, which is a fresh install:
On RHEL 7
 - omd stop
 - omd backup XY /tmp/xy.tgz

On RHEL 9
- copy over /tmp/xy.tgz
- omd restore XY /tmp/xy.tgz
