### ISSUE TITLE
WebGUI Config

### ISSUE THREAD

**Issue by Mokkujin** [ConSol/omd#21]
Hi i configured the site to start with the check_mk gui but i will get always the thruk gui first. After Login the check_mk gui login appears. 

How could i change the default gui from thruk to check_mk ?

I use it on an Raspberry PI 3 
## Raspian

Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:    8.0
Codename:   jessie
## OMD Version 

OMD - Open Monitoring Distribution Version 2.10-labs-edition

**Comment by lausser** [comment]
OMD Labs Edition uses Thruk as it's primary GUI which handles authentication. Having check_mk as entry point is only possible with the legacy version of OMD.
