### ISSUE TITLE
Create a report to csv or xlsx not in pdf format - omd 5.41

### ISSUE THREAD

**Issue by hamdyaea** [ConSol/omd#212]
We would like to generate a report in Report then generate report. Is it possible to have reports in csv or xlsx not in pdf ? from the gui or command line. We would like to have more the raw data not formated in a page.

**Comment by lausser** [comment]
Hi,
https://thruk.org/documentation/cli.html
you can periodically dump a csv/xls list with the current status data. 
Gerhard
