### ISSUE TITLE
Email notification turns to an attached file which named ATT00001.bin

### ISSUE THREAD

**Issue by jframeau** [ConSol/omd#22]
Env:
- centos 7 / omd-2.10
- Exchange 2013 

notify-by-email templates specify both content type and content transfer encoding as

Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

But mail command on CentOS doesn't recognize these directives. So when notify-by-email.pl script runs, I get:

Ignoring header field "Content-Type: text/plain; charset=utf-8"
Ignoring header field "Content-Transfer-Encoding: 8bit"

But some hardware return output with non ascii characters.

These emails are then received by Exchange like that:
Content-Type: **application/octet-stream**
Content-Transfer-Encoding: 8bit

and body as an attachment.

**Comment by sni** [comment]
Have you tried to use sendmail directly, like described here: https://labs.consol.de/omd/notifications.html

**Comment by jframeau** [comment]
ok, thx, notifications work flawlessly with stock sendmail on my CentOS 7.

I should have read more carefully omd's consol labs site.
