### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by ghost** [ConSol/omd#23]
Hi,

I have used check_mk cme edition previously, but after going through labs.consol.de i was impressed with new features.

I request you to add login page which i feel missing in labs.consol.de edition of OMD.

I really  appreciate if you can provide login page.

Thanks and Regards,
Kiran Reddy

**Comment by lausser** [comment]
There is already such a login page. Just do a
omd config set THRUK_COOKIE_AUTH on
restart and navigate to .../site/thruk

Gerhard

![omd-labs-login](https://cloud.githubusercontent.com/assets/198968/18828510/84078b40-83d8-11e6-838b-897195cf36a0.jpg)

**Comment by ghost** [comment]
Sorry I missed to check best practice part.
