### ISSUE TITLE
check_mk 1.2.8 instead of 1.2.6?

### ISSUE THREAD

**Issue by wernerflamme** [ConSol/omd#26]
It is not a real issue, but would it be possible to use the current stable version 1.2.8 of check_mk instaed of the old-stable 1.2.6? Switching to a newer version of check_mk by using the procedure described on https://monitoring-portal.org/index.php?thread/36765-upgrade-check-mk-1-2-6-to-1-2-8-omd-1-30/ removes a lot of OMD's features.

**Comment by sni** [comment]
check_mk is unmaintained in omd-labs since we do not use it ourselves or for our customers. But if someone wants to fill that gap and take care of it, just send a pull request.
