### ISSUE TITLE
virtualbox based installation error on restarting naemon core via thruk

### ISSUE THREAD

**Issue by kamacau** [ConSol/omd#27]
installed on debian / ubuntu /centos /docker (virtualbox VM)
restarting backend via thruk interface after configuring an object throw a timeout error during reload configuration and then "Warning: waiting for core reload failed."

**Comment by sni** [comment]
This has nothing todo with Thruk. A normal reload with "omd reload core" hangs as well. This is a know issue with the pnp neb module. But i hadn't found time to look into this so far.

**Comment by kamacau** [comment]
thank you, I thought it was something related to virtualbox
