### ISSUE TITLE
Problems with building 2.20 on armhf

### ISSUE THREAD

**Issue by mcasviper** [ConSol/omd#29]
When I try to build version 2.20 on armhf platform I get the following error with pymssql. The command I use is 

make deb:

setup.py: platform.libc_ver() => ('glibc', '2.4')
setup.py: Using bundled FreeTDS in /tmp/omd-2.20-labs-edition/packages/python-modules/dest/pymssql-2.1.3/freetds/nix_32
setup.py: include_dirs = ['/tmp/omd-2.20-labs-edition/packages/python-modules/dest/pymssql-2.1.3/freetds/nix_32/include', '/usr/local/include']
setup.py: library_dirs = ['/tmp/omd-2.20-labs-edition/packages/python-modules/dest/pymssql-2.1.3/freetds/nix_32/lib', '/usr/local/lib']

Installed /tmp/omd-2.20-labs-edition/packages/python-modules/dest/pymssql-2.1.3/.eggs/setuptools_git-1.1-py2.7.egg
running build
running build_ext
building '_mssql' extension
creating build
creating build/temp.linux-armv7l-2.7
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/omd-2.20-labs-edition/packages/python-modules/dest/pymssql-2.1.3/freetds/nix_32/include -I/usr/local/include -I/usr/include/python2.7 -c _mssql.c -o build/temp.linux-armv7l-2.7/_mssql.o -DMSDBLIB
_mssql.c: In function ‘init_mssql’:
_mssql.c:24578:3: warning: this decimal constant is unsigned only in ISO C90
   __pyx_v_6_mssql_MIN_INT = -2147483648;
   ^
creating build/lib.linux-armv7l-2.7
arm-linux-gnueabihf-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/_mssql.o -L/tmp/omd-2.20-labs-edition/packages/python-modules/dest/pymssql-2.1.3/freetds/nix_32/lib -L/usr/local/lib -lsybdb -lrt -o build/lib.linux-armv7l-2.7/_mssql.so
/usr/bin/ld: skipping incompatible /tmp/omd-2.20-labs-edition/packages/python-modules/dest/pymssql-2.1.3/freetds/nix_32/lib/libsybdb.a when searching for -lsybdb
/usr/bin/ld: cannot find -lsybdb
collect2: error: ld returned 1 exit status
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
Makefile:68: recipe for target 'build' failed
make[2]: *** [build] Error 1

Is there a package missing?

**Comment by lausser** [comment]
pymssql is build with a bundled freetds which contains x86 binaries. This means, an out-of-the-bx build on arm is not possible. (unless somebody is willing to port omd to arm)
