### ISSUE TITLE
Log Rotate for influxDB not working

### ISSUE THREAD

**Issue by Akira74** [ConSol/omd#32]
Hi,
just found something regarding influx DB log rotation.
Within  omd/packages/influxdb/skel/etc/logrotate.d/influxdb
you should remove the
postrotate
		###ROOT###/bin/omd reload influxdb > /dev/null
endscript
and replace it with
copytruncate
The reload doesn't work for this service... I only causes, that no log file is written  until restart.

**Comment by sni** [comment]
Could you put this into a pull request? Thanks

**Comment by m-kraus** [comment]
This change is now in PR #48

**Comment by m-kraus** [comment]
PR #48 is now merged.
