### ISSUE TITLE
`omd reload crontab` should ignore editor backup files

### ISSUE THREAD

**Issue by ahaerpfer** [ConSol/omd#33]
When rebuilding an OMD site crontab via `omd reload crontab` backup files in `etc/cron.d` with names matching `*~` (created by the Emacs editor) are *not* ignored which leads to duplicate entries in the resulting crontab.

I suppose the same might happen with automatic backups as created by other editors.

[OMD 2.20-labs-edition]

**Comment by sni** [comment]
real editors like vi create backup files like `.filename.swp` and are excluded from the pattern `etc/cron.d/*` which is used in etc/init.d/crontab ;-)
