### ISSUE TITLE
omd-2.20-labs-edition not installable on debian stretch

### ISSUE THREAD

**Issue by serenabiodec** [ConSol/omd#34]
OS distribution: Debian stretch

Content of sources list:

```
# cat /etc/apt/sources.list
deb http://deb.debian.org/debian stretch main
deb http://deb.debian.org/debian stretch-updates main
deb http://security.debian.org stretch/updates main

# cat /etc/apt/sources.list.d/labs-consol-stable.list
deb http://labs.consol.de/repo/stable/debian stretch main
```

Trying to install omd after apt-get update:

```
# apt-get install omd-2.20-labs-edition
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 omd-2.20-labs-edition : Depends: libboost-atomic1.61.0 but it is not installable
                         Depends: libboost-chrono1.61.0 but it is not installable
                         Depends: libboost-date-time1.61.0 but it is not installable
                         Depends: libboost-program-options1.61.0 but it is not installable
                         Depends: libboost-system1.61.0 but it is not installable
                         Depends: libboost-regex1.61.0 but it is not installable
                         Depends: libboost-thread1.61.0 but it is not installable
                         Depends: libicu55 but it is not installable
                         Depends: libreadline6 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

A brief check on https://packages.debian.org shows that libboost-atomic1.61.0
is available only for *sid* distribution, while libboost-atomic1.62.0 is the
package version for stretch.

Please take a look at the correspondencies between OS version and packages.

**Comment by sni** [comment]
Since the Debian testing dependencies change all the time, you cannot use the "stable" release for Debian testing but use the testing repository instead: http://labs.consol.de/repo/testing/debian

**Comment by serenabiodec** [comment]
Thank you for taking a look at this. It could be helpful to read that omd-testing are for debian-testing only somewhere in the documentation before installing it.

**Comment by serenabiodec** [comment]
The combination stretch+omd-labs consol testing is broken as well.

```
# apt-get install omd-2.21.20170317-labs-edition
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 omd-2.21.20170317-labs-edition : Depends: libreadline6 but it is not installable
```

libreadline6 is for wheezy, jessie and sid, not stretch.

I suspect that omd-testing would pair well with sid and omd-stable pairs well with jessie (I jnow that). It seems that "stretch" has somehow been left behind despite the fact that it is already in the "closed freezed" version since a month ago.

**Comment by sni** [comment]
Sorry, my fault. I always mix up testing/sid/strech etc... We don't build any stretch packages. We have packages for sid and the dependencies might be a bit behind, we don't check them every day. Pull Requests from are welcome :-)
Also the stable repository contains the releases and the testing repository the daily builds. It just that the testing repository is more up to date and therefor might contain the updated packages. We don't build old releases whenever the debian testing dependencies change.

**Comment by sni** [comment]
Anyway, i just updated the dependency. Thanks for the hint. Tomorrows daily build should be fine then.
