### ISSUE TITLE
Can't log in Thrunk after fresh install and site

### ISSUE THREAD

**Issue by Kaboofa** [ConSol/omd#37]
Hello,

I installed OMD on a CentOS Linux release 7.3.1611 (Core), created a new site, configured it to listen to 0.0.0.0:5000 without SSL and started it. When I go to http://{ip}:5000/t2/thruk, login with omd default user and password return: 

> technical problem during login, please have a look at the logfiles.

var/log/apache/error_log says:
```
auth: expected code 401, got 500
$VAR1 = bless( {
                 '_content' => 'Can\'t connect to localhost:80 (Connection refused)

LWP::Protocol::http::Socket: connect: Connection refused at /omd/sites/t2/lib/perl5/lib/perl5/LWP/Protocol/http.pm line 47.
',
                 '_headers' => bless( {
                                        '::std_case' => {
                                                          'client-date' => 'Client-Date',
                                                          'client-warning' => 'Client-Warning'
                                                        },
                                        'client-date' => 'Wed, 29 Mar 2017 12:27:27 GMT',
                                        'client-warning' => 'Internal response',
                                        'content-type' => 'text/plain'
                                      }, 'HTTP::Headers' ),
                 '_msg' => 'Can\'t connect to localhost:80 (Connection refused)',
                 '_rc' => 500,
```

Any idea of what is happening and how to solve it ?

Best regards,

**Comment by Kaboofa** [comment]
Hi,

Seems to affect OMD only when `APACHE_MODE ` is set to `own`.
  
Following command solved the issue: `omd config set APACHE_MODE ssl`.

Regards,

**Comment by sni** [comment]
When chaning the apache_mode, you have to restart the system apache as root. This cannot not happen automatically. Also make sure your system apache listens correctly to 80/443.
