### ISSUE TITLE
omd-nc 1.11 issue with livestatus while using multi-site

### ISSUE THREAD

**Issue by aadi4u** [ConSol/omd#4]
I am using centos 6.3 32 bit and used the build omd-nc-1.11.20140702.rhel6.i386.rpm  
I am getting the following error while using multisite
Livestatus problem: Unhandled exception: 400: Table 'hostsbygroup' has no column 'host_comments_with_extra_info'

Do I need to patch it?

Thanks
Ashish

**Comment by nitin-tm** [comment]
Have this column is added to livestatus ?

**Comment by nitin-tm** [comment]
I have another error Unhandled exception: 400: Table 'services' has no column 'service_comments_with_extra_info'.

**Comment by sni** [comment]
I'd be happy to accept patches herefor but i don't have time to investigate this myself as i don't use check_mk at all.

**Comment by sni** [comment]
the repository is here: https://github.com/naemon/naemon-livestatus
So if anybody is working on that, just send patches over there and they will be automatically to OMD here.

**Comment by hellraiser2005** [comment]
Switched to daily build, clean install of ubuntu 16.04 LTS and omd.
Still error "Unhandled exception: 400: Table 'hosts' has no column 'host_comments_with_extra_info'"

**Comment by robertmbaker** [comment]
@sni 
I came across this issue for the same reason others have, but I am curious about a prior comment you made.

"i don't have time to investigate this myself as i don't use check_mk at all."

OMD doesn't have enough documentation for me to determine what you *are* using. Can you please elaborate what it is you do use, and how?

**Comment by sni** [comment]
well, basically everything in omd except cmk. But that shouldn't matter. OMD is a collection of tools and you don't have to use them all.

**Comment by robertmbaker** [comment]
Understood, I have used Nagios before without check_mk, but this is my first go at using OMD. I guess the question I have is what tool are you using for configuring the core? Or do you edit config files manually?

Are you perhaps just using Thruk to configure the core?

**Comment by kaitoan2000** [comment]
tail -f /omd/sites/demo/var/naemon/livestatus.log

> 2017-10-30 07:52:28 error: Table 'services' has no column 'service_comments_with_extra_info'
> 2017-10-30 07:52:30 error: Table 'hosts' has no column 'host_comments_with_extra_info'
> 2017-10-30 07:52:30 error: Table 'hosts' has no column 'host_comments_with_extra_info'


I found this error with OMD - Open Monitoring Distribution Version 2.60-labs-edition/Centos 7
Any help?

**Comment by noxxsan** [comment]
same problem here OMD - Open Monitoring Distribution Version 2.20-labs-edition

root@nagios:~# tail -f /omd/sites/wifi/var/naemon/livestatus.log
2017-11-23 15:49:28 error: Table 'hosts' has no column 'host_comments_with_extra_info'
2017-11-23 15:49:36 error: Table 'hostsbygroup' has no column 'host_comments_with_extra_info'
2017-11-23 15:49:43 error: Table 'hostsbygroup' has no column 'host_comments_with_extra_info'
2017-11-23 15:54:49 error: Table 'hostsbygroup' has no column 'host_comments_with_extra_info'
2017-11-23 15:54:59 error: Table 'hostsbygroup' has no column 'host_comments_with_extra_info'
2017-11-23 15:55:54 error: Table 'hostsbygroup' has no column 'host_comments_with_extra_info'
2017-11-23 15:55:59 error: Table 'hostsbygroup' has no column 'host_comments_with_extra_info'
2017-11-23 15:56:05 error: Table 'hostsbygroup' has no column 'host_comments_with_extra_info'
2017-11-23 15:56:10 error: Table 'hostsbygroup' has no column 'host_comments_with_extra_info'
2017-11-23 15:56:25 error: Table 'hostsbygroup' has no column 'host_comments_with_extra_info'

**Comment by kfarrar** [comment]
I needed to import many (several hundred) target hosts into an OMD system, but did not find a simple way to do this in thruk (and wanted to avoid writing hosts file manually or via bulk ansible jinja2 templates...).

I managed to get my OMD 2.60 system working with CSV bulk imported hosts via check_mk, and ran into this error message. Changing the monitoring core made the error messages stop.

Switching the monitoring core from naemon to nagios might fix this problem

See the following two links for livestatus versus naemon issues

https://monitoring-portal.org/index.php?thread/41333-unhandled-exception-400-table-hosts-has-no-column-host-comments-with-extra-info/ 
Unhandled exception: 400: Table 'hosts' has no column 'host_comments_with_extra_info'


https://www.monitoring-lists.org/archive/naemon-users/2015-February/000070.html
Subject: Livestatus version with OMD/naemon

**Comment by ecoop3r** [comment]
> I needed to import many (several hundred) target hosts into an OMD system, but did not find a simple way to do this in thruk (and wanted to avoid writing hosts file manually or via bulk ansible jinja2 templates...).
> 
> I managed to get my OMD 2.60 system working with CSV bulk imported hosts via check_mk, and ran into this error message. Changing the monitoring core made the error messages stop.
> 
> Switching the monitoring core from naemon to nagios might fix this problem
> 
> See the following two links for livestatus versus naemon issues
> 
> https://monitoring-portal.org/index.php?thread/41333-unhandled-exception-400-table-hosts-has-no-column-host-comments-with-extra-info/
> Unhandled exception: 400: Table 'hosts' has no column 'host_comments_with_extra_info'
> 
> https://www.monitoring-lists.org/archive/naemon-users/2015-February/000070.html
> Subject: Livestatus version with OMD/naemon

Also changed to nagios core and it's working.  Thanks
