### ISSUE TITLE
Error on sharing Grafana Panel

### ISSUE THREAD

**Issue by rockaut** [ConSol/omd#41]
Wenn man dem "Direct link rendered image" zum Sharen der Grafik nutzt, kommt nur:

`Server side error :(
Failed to render to png`

Im grafana.log steht:
`t=2017-04-05T15:21:37+0200 lvl=eror msg="Failed to update dashboard json index [lstat /omd/sites/datacenter/var/grafana/dashboards: no such file or directory]"`

**Comment by rockaut** [comment]
Version 2.20-labs-edition auf Ubuntu 14.04

**Comment by Griesbacher** [comment]
This folder is added with: aafb438ff3321eb33bab77db7fb4352d3fcb64fd
But phantomjs is currently not where Grafana expects it, I'll look into it.
