### ISSUE TITLE
live status patch not working on nightly build

### ISSUE THREAD

**Issue by AllwynPradip** [ConSol/omd#42]
Does the nightly build compile the patches that are added . i have been using the current nightly build 2.21.20170513-labs-edition  but i still get the error on live status when using naemon or icinga2 core for not having column names.

https://github.com/ConSol/omd/commit/274e45e07da123ccac65f7ac78dde249ea2d0b4f

Can you check on this please.

![image](https://cloud.githubusercontent.com/assets/4199611/26024927/eff8af0c-37f9-11e7-8de5-f323093cef8c.png)

![image](https://cloud.githubusercontent.com/assets/4199611/26024916/c39c4d9c-37f9-11e7-94fa-b3a74aae9d00.png)

**Comment by sni** [comment]
Yes, the patch file is used in the nightlys. However, the patch is for naemon only, not for icinga2.

**Comment by AllwynPradip** [comment]
the above screenshot is for naemon core. its does not seem to be working.

**Comment by AllwynPradip** [comment]
your update on this will be appreciated.

**Comment by AllwynPradip** [comment]
#49
