### ISSUE TITLE
Graphana light theme hardcoded

### ISSUE THREAD

**Issue by Thiagor-it** [ConSol/omd#43]
Hello,

I know that the light theme is harcoded on Grafana and that i can append theme=dark on the URL to change it, but i'm having some issues while playing thourgh a playlist. 

I put the theme=dark on the playlist page and click on Play, so the dashboards began to rotate with the dark theme, but after a while the browser auto-refresh the page and then the theme=dark is gone and the dashboards starts to display in light theme.

Is there a way for me to change this behaviour? Sorry for the lack ok knowledge, but can i recompile Grafana without the hardcoded theme and without broking anything on OMD?

Thanks!
Thiago

**Comment by Griesbacher** [comment]
Hi Thiago,

like you said, it is hard coded, but you could build Grafana on your own or use the official pre build binary and replace the shipped one. 

If you want to build it on your own, you could also use the OMD package, just remove this [patch](https://github.com/ConSol/omd/blob/labs/packages/grafana/patches/0001-force-light-theme.patch) and use the ```make build``` command in the grafana package folder. Therefore you'll need to build go1.4 and go1.8 in this order, as dependencies. Then you could replace the binary in your installed OMD version, but beware if you update your OMD you'll have to take of that binary.

I hope this helps and best regards,
Philip
