### ISSUE TITLE
multisite_cookie_auth

### ISSUE THREAD

**Issue by bong0** [ConSol/omd#44]
Hi,

Shouldn't those two files:
  * https://github.com/ConSol/omd/blob/labs/packages/check_mk/MULTISITE_COOKIE_AUTH.hook#L28
  * https://github.com/ConSol/omd/blob/2638f45561828a93a6c1ff65064c0da5481d87b1/packages/downtime-api/DOWNTIMEAPI.hook

generate an apache 2.4 compatible config? When upgrading omd to 2.4 labs edition, those files were newly written causing apache to refuse starting.

**Comment by sni** [comment]
I can't say anything about cmk, but the downtime api should just work and there are unit and integration tests to ensure that. Please reopen if the issue still persists in the latest release.
