### ISSUE TITLE
DBD + MSSQL does not appear to work in OMD Labs 2.40

### ISSUE THREAD

**Issue by mintsoft** [ConSol/omd#45]
Hello,

Using `./check_mssql_health` under OMD-Labs 2.40 on Debian Jessie appears to be broken, All attempts to connect to an MSSQL Server result in `Adaptive Server connection failed`; 

It looks like the libct isn't quite compiled consistently with the Debian Jessie released package:
```
rob@box:/usr/lib/x86_64-linux-gnu$ ldd libct.so.4
        linux-vdso.so.1 (0x00007ffd6313e000)
        libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007fadc7219000)
        libgnutls-deb0.so.28 => /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28 (0x00007fadc6efa000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fadc6cf6000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fadc6ad9000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fadc672e000)
        libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007fadc645a000)
        libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007fadc6229000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fadc6025000)
        libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007fadc5e19000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007fadc5c15000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fadc59fe000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fadc57e3000)
        libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007fadc559d000)
        libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007fadc5389000)
        libnettle.so.4 => /usr/lib/x86_64-linux-gnu/libnettle.so.4 (0x00007fadc5157000)
        libhogweed.so.2 => /usr/lib/x86_64-linux-gnu/libhogweed.so.2 (0x00007fadc4f28000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fadc4ca5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fadc76b9000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fadc4a9c000)
```

vs the OMD version:

```
rob@box:/omd/versions/2.40-labs-edition/lib$ ldd libct.so.4
                linux-vdso.so.1 (0x00007fffd5374000)
                libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f30a9588000)
                libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f30a936b000)
                libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f30a8fc0000)
                /lib64/ld-linux-x86-64.so.2 (0x00007f30a99e0000)
```

Installing the libct4 package and symlinking `/omd/versions/2.40-labs-edition/lib/libct.so.4` to `/usr/lib/x86_64-linux-gnu/libct.so.4` makes it work again

Thanks,
Rob

**Comment by infraweavers** [comment]
We have this problem too, this is still a problem with `OMD-2.60-labs-edition`

**Comment by infraweavers** [comment]
@lausser it looks like `check_mssql_health` doesn't work at all under OMD 2.60 as perl-dbi for sybase is totally unhappy. I can't get this to work in circumstance; it looks (based on https://monitoring-portal.org/woltlab/index.php?thread/41271-upgrade-from-omd-1-30-to-2-4-broke-sybase-dbd/&postID=252396#post252396) that there might be an issue with `libct` ?

**Comment by mintsoft** [comment]
@infraweavers it looks like there's a massive difference between building `libct` using `make` (which is what omd does); if you build `libct` using:
```
apt source libct4
dpkg-buildpackage -us -uc
```
it asks for extra dependencies (`unixodbc-dev (>= 2.2.11-10)` `libkrb5-dev`) and builds with wider support.

I'm not sure exactly how to get omd to build it correctly yet, however I'm trying to figure it out

**Comment by infraweavers** [comment]
@mintsoft `dpkg-buildpackage` will use the override configure that's in the debian/rules file:

```
override_dh_auto_configure:
        dh_auto_configure -- --with-gnu-ld --with-tdsver=4.2 \
                --with-unixodbc=/usr --sysconfdir=/etc/freetds \
                --enable-sybase-compat --with-gnutls --enable-krb5
```

**Comment by lausser** [comment]
```
OMD[test]:~$ cat /etc/debian_version 
8.10
OMD[test]:~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
OMD[test]:~$ 
OMD[test]:~$ lib/nagios/plugins/check_mssql_health --mode connected-users --hostname 10.0.15.62 --port 1433 --username sa --password 'Sommer10!' --commit 
OK - 3 connected users | 'connected_users'=3;50;80;;
```
I don't see a problem and i haven't heard of any problems at our customers.

**Comment by lausser** [comment]
```
OMD[test]:~$ cat /etc/debian_version 
8.10
OMD[test]:~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
OMD[test]:~$ 
OMD[test]:~$ lib/nagios/plugins/check_mssql_health --mode connected-users --hostname 10.4.1.1 --port 1433 --username sa --password '***' --commit 
OK - 3 connected users | 'connected_users'=3;50;80;;
```
I don't see a problem and i haven't heard of any problems at our customers.

**Comment by infraweavers** [comment]
@lausser Apologies, you're absolutely right. `check_mssql_health` works under OMD 2.60 (I think it was PICNIC before). The issue I'm actually experiencing is that other FreeTDS nagios checks (for example https://github.com/danfruehauf/nagios-plugins/tree/master/check_sql) don't work when run within OMD however they do work when they're run as me (for example); it was working before we upgraded to OMD 2.x. They use DBD to access mssql, so I'm guessing it's a different path that leads to this.

Judging by https://github.com/ConSol/omd/issues/45#issuecomment-371507440 and https://github.com/ConSol/omd/issues/45#issuecomment-371512035 it looks like freeTDS being built different (i.e not having `--with-gnu-ld --with-tdsver=4.2  --with-unixodbc=/usr --enable-sybase-compat --with-gnutls --enable-krb5`. 

I've changed that configure line and am currently rebuilding omd to see if that resolves the problem; if it does I'll put a PR in for it?

**Comment by lausser** [comment]
Did the configure parameters help?

**Comment by infraweavers** [comment]
I've not been able to get it to compile with all those parameters on yet as freeTDS needs gnutls building as well and I've not managed to get GnuTLS's build to be available to the FreeTDS build as I don't think I understand how build dependencies are resolved.  @lausser

**Comment by lausser** [comment]
Please keep in mind that OMD tries to make use from distribution packages as much as possible. (as long as they are available for all of the supported distributions). 
In the distros subdirectory there are Makefiles for all of them. And here we distinguish between OS-packages which become dependencies of the omd package, and BUILD-packages, which are needed during compiling.
So in this case, libgnutls-deb0-28 and libgnutls28-dev might be the candidates.

**Comment by infraweavers** [comment]
@lausser We've got it reproduced here at the moment, if we add ` --with-tdsver=4.2 ` to the configure then it fixes `check_sql` against our SQL Server 2005 install; I've eliminated everything except the `with-gnutls` to fix some of our PHP checks, however I can't get that to compile yet
