### ISSUE TITLE
Email notification with grafana graph issue

### ISSUE THREAD

**Issue by musklor** [ConSol/omd#46]
https://monitoring-portal.org/index.php?thread/41330-email-notification-with-grafana-graph-issue/

Omd labs 2.40 with defaults options.
When I enable grafana/histou/influxdb/nagflux my email notification contains the Thruk homepage.(Host-perf and srv-perf in my remplages)

I used this article : https://labs.consol.de/omd/grafana_graphing.html

**Comment by musklor** [comment]
Remplages=Templates :)

**Comment by sni** [comment]
Have you tried the nightlys?

**Comment by musklor** [comment]
Not yet

Le 27 juillet 2017 14:25:02 GMT+02:00, Sven Nierlein <notifications@github.com> a écrit :
>Have you tried the nightlys?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ConSol/omd/issues/46#issuecomment-318346909

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by musklor** [comment]
Ok, solved with the last nightly. Thanks!! Great Work !
