### ISSUE TITLE
Add SLES 12 SP3 packages

### ISSUE THREAD

**Issue by abroc** [ConSol/omd#50]
Hi,
will you add package for SLES12 SP3? If I want to build OMD-Labs from source, procedure is same:
#> git clone https://github.com/ConSol/omd.git
#> cd omd
#> ./configure
#> make && make rpm

Of course before run .\configure create Makefile.SLES_12SP3 in distros folder.

Thanks,
Jan

**Comment by sni** [comment]
Only configure and "make rpm" is required to build omd from source. And yes, sooner or later we will add SLES12SP3 as well. Pull requests are welcome.

**Comment by sni** [comment]
sles12sp3 packages are available now.
