### ISSUE TITLE
omd labs edition 2.40 can't be installed on Raspberry Pi 3 running Raspbian stretch

### ISSUE THREAD

**Issue by x2k13** [ConSol/omd#53]
Since armhf packages are missing from both stable and testing repositories matching debian stretch, we have no chance in installing omd labs edition on a Rpi 3 running Raspbian Stretch (2017-09-07).

armhf packages are available in jessie, but they won't install on stretch due to missing dependencies (packages that were already updated in stretch beyond the needed versions in jessie).

Since downgrading to an older raspbian jessie image is quite nonsense (and close to impossible since the foundation doesn't even offer a download for jessie anymore), are there any plans to populate the stretch repos with needed armhf packages?

Thanks for your help in advance.

**Comment by sni** [comment]
armhf packages are a personal side project of @lausser and we don't build them automatically or on a regular basis. So right now i am not aware of any plans to build stretch packages. But you could try to build them yourself, just clone the repository and run `./configure && make deb`.

**Comment by lausser** [comment]
apt-get update; apt-cache search omd ..... you should see omd-2.60-labs-edition now.

**Comment by thomasleitner** [comment]
Hi,
Just tried this and still cannot find omd-labs-edition or similar. I'm using the latest raspbian stretch:

```
> root@omd:~# apt-get update; apt-cache search omd
> Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
> Hit:2 http://mirrordirector.raspbian.org/raspbian stretch InRelease
> Reading package lists... Done
> cp2k - Ab Initio Molecular Dynamics
> customdeb - Modfies binary Debian package
> dicomnifti - converts DICOM files into the NIfTI format
> golang-github-armon-gomdb-dev - LMDB for Go - OpenLDAP Lightning Memory-Mapped Database
> isomd5sum - ISO9660 checksum utilities
> libnet-dns-fingerprint-perl - library to determine DNS server vendor, product and version
> libtemplate-provider-fromdata-perl - module to load templates from your __DATA__ section
> node-array-flatten - Flatten nested arrays
> php-fdomdocument - extension to PHP's standard DOM
> python-pyisomd5sum - ISO9660 checksum Python module
> python-zc.customdoctests - Use Python doctest with other languages
> python3-pyisomd5sum - ISO9660 checksum Python 3 module
> python3-zc.customdoctests - Use doctest with other languages (Python 3)
> tofrodos - Converts DOS <-> Unix text files, alias tofromdos
> vrflash - tool to flash kernels and romdisks to Agenda VR
> `root@omd:~#
```

Any ideas? 

Thanks // Tom
