### ISSUE TITLE
Core needs to be reloaded when config objects

### ISSUE THREAD

**Issue by amateo** [ConSol/omd#54]
I have upgraded my previous omd 1.20 monitoring server to a new one with omd-labs-edition 2.60.
The configuration is working fine and monitoring is done, but my problem is when I try to modify configuration (in any of my omd sites) from thruk interface.
The configuration change is done, but when I try to apply or check the configuration change ar error message is displayed saying `config check failed !` and putting the mouse over it displays `Core needs to be reloaded`.
I have checked the configuration from commandline with `~/etc/init.d/nagios checkconfig`, but no error is displayed and if I manually reload nagios (from commandline) it is reloaded without any problem.
Any help?

**Comment by sni** [comment]
Sounds like you didn't configure a reload command.
