### ISSUE TITLE
Check_MK 1.4

### ISSUE THREAD

**Issue by jowanw** [ConSol/omd#57]
Is it possible to update Check_MK to the new stable version?

**Comment by sni** [comment]
Pull requests are welcome to update things, right now, nobody maintains cmk here.

**Comment by 4oo4** [comment]
Is check_mk still going unmaintained? If so, would really like to see that updated. I would be willing to help maintain it if need be but wouldn't be able to do it alone.

**Comment by sni** [comment]
nothing changed
