### ISSUE TITLE
Upgrade OMD 1.2 to OMD 2.6 considering

### ISSUE THREAD

**Issue by ninhvguyen-vn** [ConSol/omd#58]
Hi OMD team,

I am collecting information to make a plan to upgrade OMD 1.2 to OMD 2.6.
I have a couple of questions as below:
-Is it possible to upgrade existing OMD 1.2 to 2.6? Is there any document for upgrade steps?
-Why is Nagios Core still 3.5.1 but not 4.x.x in OMD 2.6
-Do i need to upgrade Check_MK, Java to compatible with OMD 2.6?
Thanks and regards!
Ninh

**Comment by sni** [comment]
> -Is it possible to upgrade existing OMD 1.2 to 2.6? Is there any document for upgrade steps?

Sure, thats no problem. There are no additional documentations for that, its a simple `omd update`

> -Why is Nagios Core still 3.5.1 but not 4.x.x in OMD 2.6

We have naemon instead of nagios 4.

> -Do i need to upgrade Check_MK, Java to compatible with OMD 2.6?

OMD has nothing to do with java.
