### ISSUE TITLE
OMD with Grafana does not show bandwidth Info

### ISSUE THREAD

**Issue by mskrishna20051974** [ConSol/omd#64]
Hi,

I installed OM 2.7 with thruk, check_mk and grafana. 
However when i tried to look at the interface traffic graphs, i get the info in packets not the bandwidth as bits/sec.

If i use pnp4nagios, it works fine.

Please suggest on how to fix this.

**Comment by sni** [comment]
please use this bug tracker for bugs only. Community support is available via various channels, ex.: 
 - http://docs.grafana.org/support/
 - https://monitoring-portal.org/
