### ISSUE TITLE
Ubuntu 18.04 apt install - why no package shown?

### ISSUE THREAD

**Issue by wytcld** [ConSol/omd#65]
Added the key and repository, run apt update, but no "omd" package shows up as installable. Have looked with both apt-cache and aptitude -- nothing with "omd" or "OMD" in the name.

**Comment by sni** [comment]
there are no packages for ubuntu 18.04 in the 'stable' repository yet. Use the 'testing' repository instead.

**Comment by wytcld** [comment]
Thanks. The documentation has run ahead of the reality. https://labs.consol.de/repo/stable/ implies 18.04 is ready to go. Not complaining; just overly trusting of docs.
