### ISSUE TITLE
On Ubuntu 16 with omd 2.70: omd init.d script missed by omd setup

### ISSUE THREAD

**Issue by wytcld** [ConSol/omd#66]
Activating init script for "omd"
Going to execute 'update-rc.d omd defaults'
update-rc.d: error: initscript does not exist: /etc/init.d/omd
ERROR

There is however an /etc/init.d/omd-2.70-labs-edition, but symlinking that to omd doesn't do it:

Activating init script for "omd"
Going to execute 'update-rc.d omd defaults'
insserv: script omd is a symlink to another script, skipped!

Copying that to omd doesn't work either:

Activating init script for "omd"
Going to execute 'update-rc.d omd defaults'
insserv: script omd: service omd-2.70-labs-edition already provided!
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
ERROR

Having no prior experience with omd setup, should I expect it has done enough despite this?

**Comment by sni** [comment]
How did you install OMD?
