### ISSUE TITLE
Downtime API returning status 500 with "error": "Thruk found no backends"

### ISSUE THREAD

**Issue by Alfaj0r** [ConSol/omd#67]
Howdy,
I'm hitting https://omdsrv1/site3/api/downtime?host=myserver&comment=testing&duration=60
and getting an answer of:
```
{
    "status": 500, 
    "backends": [], 
    "params": {
        "comment": "test", 
        "duration": "60", 
        "host": "myserver"
    }, 
    "error": "Thruk found no backends", 
    "originating_ip": "10.0.10.33"
}
```

If I modify my URL to include a backend with: https://omdsrv1/site3/api/downtime?host=myserver&comment=testing&duration=60&backend=site3  I notice that the "backends" line still reads as an empty array with []. and my line is showing in the "params" section:
```
{
    "status": 500, 
    "backends": [], 
    "params": {
        "comment": "test", 
        "duration": "60", 
        "host": "myserver"
        "backend": "site3"    
    }, 
    "error": "Thruk found no backends", 
    "originating_ip": "10.0.10.33"
}
```

I have two OMD servers, and seven sites. I've tried all sorts of combinations to see if I can magically end with the right request, but no luck.
What am I missing??

**Comment by Alfaj0r** [comment]
Oh yeah, running OMD 2.7 :)

**Comment by lausser** [comment]
Try this as site3 on your omdsrv1:
$OMD_ROOT/bin/thruk -b ALL -A omdadmin 'extinfo.cgi?type=0&view_mode=json'

You should get a json hash with all the backends you configured for site3.

**Comment by Alfaj0r** [comment]
Thanks Gerhard!
Here are all the lines that say "backend" 
```
var initial_backends = {"3f6be":{"version":"3.5.1","name":"site3","state":0,"key":"3f6be","data_src_version":"Livestatus 1.2.8p20","cls":"UP","last_error":"site3: OK","program_start":1540853968}};
var backend_keys     = ["3f6be"];
var current_backend_states;
var backend_chooser     = 'select';
var param_backend       = [""];
var backend_chooser     = 'select';
```
Unfortunately, I'm not really sure what to do with this info... Do I use the backend_keys to make my API call, or something similar?

**Comment by lausser** [comment]
$OMD_ROOT/bin/thruk -b ALL -A omdadmin 'extinfo.cgi?type=0&view_mode=json'

**Comment by Alfaj0r** [comment]
Sorry, I don't follow.

**Comment by Alfaj0r** [comment]
Also, worth mentioning ( I hope):
the file /tmp/run/downtimeapi.trace is not logging anything, it's still at 0 bytes, even when I hit the API and get the 500 result.

**Comment by Alfaj0r** [comment]
One more detail.
I added a secret token to a host, so I can test calling the API from a different source (my own laptop in this case). I see my "dtauthtoken" show up in the params, and the response is the same as before... so in my ignorant mind this now suggests my issue is even pre-authentication.

Here's the latest response:
```
{
    "status": 500, 
    "backends": [], 
    "params": {
        "comment": "test", 
        "duration": "5", 
        "host": "myserver", 
        "dtauthtoken": "supersecret234abc"
    }, 
    "error": "Thruk found no backends", 
    "originating_ip": "10.99.90.27"
}
```

**Comment by lausser** [comment]
$OMD_ROOT/bin/thruk -b ALL -A omdadmin 'extinfo.cgi?type=0&view_mode=json'
is a command which you should run as user site3 on the command line.

**Comment by Alfaj0r** [comment]
Right. I've done that, and shared some of the output.
I don't understand what to do after that. Can you explain what the next steps should be?

**Comment by lausser** [comment]
When i run the command
```
OMD[prod@lx111]:~$ $OMD_ROOT/bin/thruk -b ALL -A omdadmin 'extinfo.cgi?type=0&view_mode=json'
{
   "e7be8" : {
      "accept_passive_host_checks" : 1,
      "accept_passive_service_checks" : 1,
      "addr" : "/omd/sites/prod/tmp/run/live",
      "check_external_commands" : 1,
      "check_host_freshness" : 1,
      "check_service_freshness" : 1,
      "data_source_version" : "Livestatus 1.2.8p20",
      "disabled" : 0,
      "enable_event_handlers" : 1,
      "enable_flap_detection" : 0,
      "enable_notifications" : 1,
      "execute_host_checks" : 1,
      "execute_service_checks" : 1,
      "interval_length" : 60,
      "last_command_check" : 1541163502,
      "last_error" : "",
      "last_log_rotation" : 1541113200,
      "nagios_pid" : 8926,
      "name" : "gsprod",
      "obsess_over_hosts" : 0,
      "obsess_over_services" : 0,
      "peer_addr" : "/omd/sites/prod/tmp/run/live",
      "peer_key" : "e7be8",
      "peer_name" : "prod",
      "process_performance_data" : 1,
      "program_start" : 1541008294,
      "program_version" : "3.5.1",
      "running" : 1,
      "section" : "Default",
      "state" : 0,
      "type" : "livestatus"
   }
}
```
i see something that does not look like the snippets you posted above.

**Comment by Alfaj0r** [comment]
Ah, thank you for that clarification.
Indeed, that is not what I got. Here's the full output: https://pastebin.com/raw/GXu6RuCz (pasting it in here kept applying formatting, sorry)

**Comment by sni** [comment]
if you simply need the backend ids, run `thruk -l`

**Comment by lausser** [comment]
Did you change something in the etc/thruk/cgi.cfg after the OMD create?

**Comment by Alfaj0r** [comment]
sni,
What I need is to figure out how to get my API call to succeed. Even if I know my backend's ID, I wouldn't know what to do with that information next.

**Comment by Alfaj0r** [comment]
> Did you change something in the etc/thruk/cgi.cfg after the OMD create?


Good question. I don't even see /etc/thruk/.
I'm going to loop in my linux admin for a little more in-depth investigation.

**Comment by lausser** [comment]
In an OMD environment it's /omd/sites/site3/etc/thruk/cgi.cfg

**Comment by Alfaj0r** [comment]
> if you simply need the backend ids, run `thruk -l`

```
OMD[site3]:~$ thruk -l
Def   Key      Name        Address
-------------------------------------------------
 *   3f6be    site3  /omd/sites/site3/tmp/run/live (OK)
-------------------------------------------------
OMD[site3]:~$ 
```

What is the next step now in making my API call work?

**Comment by Alfaj0r** [comment]
> In an OMD environment it's /omd/sites/site3/etc/thruk/cgi.cfg

I'm told that "The only changes that have been made in $OMD_ROOT/etc/cgi.cfg are adding admin users."

**Comment by Alfaj0r** [comment]
And on that note, we've made sense of why "$OMD_ROOT/bin/thruk -b ALL -A omdadmin 'extinfo.cgi?type=0&view_mode=json'" wasn't running. Now with an actual admin user...


```
OMD[site3]:~$ $OMD_ROOT/bin/thruk -b ALL -A actualuserhere 'extinfo.cgi?type=0&view_mode=json'
{
   "3f6be" : {
      "accept_passive_host_checks" : 1,
      "accept_passive_service_checks" : 1,
      "addr" : "/omd/sites/site3/tmp/run/live",
      "check_external_commands" : 1,
      "check_host_freshness" : 1,
      "check_service_freshness" : 1,
      "data_source_version" : "Livestatus 1.2.8p20",
      "disabled" : 0,
      "enable_event_handlers" : 1,
      "enable_flap_detection" : 1,
      "enable_notifications" : 1,
      "execute_host_checks" : 1,
      "execute_service_checks" : 1,
      "interval_length" : 60,
      "last_command_check" : 1541175092,
      "last_error" : "",
      "last_log_rotation" : 1541142000,
      "nagios_pid" : 2622,
      "name" : "site3",
      "obsess_over_hosts" : 0,
      "obsess_over_services" : 0,
      "peer_addr" : "/omd/sites/site3/tmp/run/live",
      "peer_key" : "3f6be",
      "peer_name" : "site3",
      "process_performance_data" : 1,
      "program_start" : 1541117007,
      "program_version" : "3.5.1",
      "running" : 1,
      "section" : "Default",
      "state" : 0,
      "type" : "livestatus"
   }
}

**Comment by lausser** [comment]
That's how it should look like. But the downtime API uses the omdadmin user. 

So ...adding admin users… looks like omdadmin was _replaced_, not like extra users were _added_.

**Comment by Alfaj0r** [comment]
That is an excellent distinction. Thank you for that insight!
Is there a way to make the API use another user? Or is the only path forward to re-add omdadmin?

**Comment by Alfaj0r** [comment]
I see. I really appreciate your explanation, and your _patience_!

Query: can we make the downtime API use another user account? Or is the only path forward to re-add omdadmin?

**Comment by Alfaj0r** [comment]
Re-added omdadmin and the API works just fine now. Get a 200 response, downtime is scheduled.... yay!

I appreciate the guidance and the patience on this one!

**Comment by rgelber** [comment]
Thanks for the thread @Alfaj0r! At the ConSol team, can you guys update your downtime API documentation? It would probably be best to inform users that they need omdadmin to be present in $OMD_ROOT/etc/thruk/cgi.cfg. With my current config, I removed the user and have been using LDAP authentication to access my Thruk dashboard. I would assume others are doing that as well.
