### ISSUE TITLE
Problem with Business Process

### ISSUE THREAD

**Issue by r4f4m4r** [ConSol/omd#68]
I have a problem with the business process, I have omd labs 2.80. When i try create a BP in thruk, this do all fine but, don´t create the host or the service for that i can see this in icinga. I create the BP, I save the changes, but I do not know can see the host that has to create anywhere.

The message says:
"This service does not exist...
If you believe this is an error, check your monitoring configuration and make sure all backends are connected."

but the backend configuration is auto, I tried to change it to the IP and the livestatus port, but the error is the same.

**Comment by r4f4m4r** [comment]
I have seen that the config stores it in the icinga2 directory, if I change the core with the omd config to icinga2 it works, but if I put it in icinga 1, nagios, or some other, nothing is seen.

the config is in omd / opt / sites / %%% / etc / thruk / thruk_local.d / omd_core.conf.
But the file says "this file will be overwritten by the CORE hook, do not change manually"
but with the omd config it does not change

**Comment by sni** [comment]
I cannot reproduce that issue, Thruk creates the file `etc/icinga/conf.d/thruk_bp_generated.cfg` by default unless you configured something else. You can use `omd diff` to see where your configs differ from the defaults.
