### ISSUE TITLE
mobile interface broken

### ISSUE THREAD

**Issue by ghost** [ConSol/omd#7]
Hello,

Version 1.85-20141009
OMD 1.21-nc.20141009
(from consol repo)

Mobile interface broken and unresponsive. (when clicking anything - just refreshes the page)
Attaching an image.
![mobile](https://cloud.githubusercontent.com/assets/7058053/5025313/fcc3a90c-6b1f-11e4-9bab-a9ecb9205172.jpeg)

**Comment by beinbliss** [comment]
Hello,

unfortunately it isn't fixed, i have updated to omd-nc.20141122 from consol repo and the issue remains the same.

**Comment by sni** [comment]
yes, omd-nc builds are broken atm, so the build from november does not have that fix yet. I will have a look into that as soon as i can.

**Comment by beinbliss** [comment]
ok thanks
