### ISSUE TITLE
pnp4nagios PHP sessions / tmpfs  & memory exhaustion

### ISSUE THREAD

**Issue by infraweavers** [ConSol/omd#70]
We have a web application that hits /pnp4nagios/xport/json?host=iisServer&srv=CheckName&view=0&source=0 a considerable number of times each minute so that it can display performance stats for our IIS tier.

This results in creation of 400 php session files (tmp/php/session) each minute.

That means we are, in any given 24 hour period, creating enough session files to fill tmpfs (/omd/sides/SITENAME/tmp) to the extent there is significant memory pressure and the OOM Killer kicks in.

omd tmpfs by default will use 50% of RAM (on a system without swap enabled). On OMD servers with <= 4GB RAM this seems particularly problematic.

We've fixed this by reducing the size of tempfs and adjusting the cron job (https://github.com/ConSol/omd/blob/labs/packages/apache-omd/skel/etc/cron.d/php-sessions) to run every 10 minutes and remove session files over 60 minutes old.

We would like to share a few thoughts on how this could be resolved:

1) pnp4nagios should not create a session when hitting, for example, /pnp4nagios/xport, as it is not needed?

2) pnp4nagios should be configurable as to turn off sessions

3) The cron job runs more often and gets more aggressive in its cleanup of php sessions when omd tmpfs exceeds a given size

4) omd tmpfs should be smaller (by default) on hosts with <= 4GB RAM

**Comment by sni** [comment]
1. please open an issue for pnp4nagios on this (https://github.com/lingej/pnp4nagios/)
2. see 1.
3. i'd favor disabling tmpfs in those cases
4. tmpfs can be disabled via `omd config`
