### ISSUE TITLE
omd backup, as root, complains must be run as root

### ISSUE THREAD

**Issue by wytcld** [ConSol/omd#71]
[root prompt] omd backup /tmp/site_test_backup.tgz
omd: You need to execute omd as root or site user.
[stops]

That leaves obscure what to do to back up a multisite OMD.

Then as the site user, for what is after all a single-site setup:

$ omd backup /tmp/site_test_backup.tgz
Warning: The site should be stopped for a backup.
[goes on, despite warning -- maybe better if it prompted for okay?]

Which is a wise warning, and might be mentioned on https://labs.consol.de/omd/backup_and_restore.html.

**Comment by sni** [comment]
the error message is a bit misleading, but when running omd as root, the first parameter after the command is used as site name. Therefor it trys to `su` into the user `/tmp/site_test_backup.tgz` which obviously does not exist.

**Comment by sni** [comment]
hopefully made it clearer with: cd6c1839478ce642813d6a33f3a8415b4f994535
