### ISSUE TITLE
Please included latest check_nrpe 2.x (plugin)

### ISSUE THREAD

**Issue by wAmpIre** [ConSol/omd#73]
Hi!

Please include latest NRPE plugin 2.x (ATM 2.15). There's so much software in the wild which does NOT work with (at least some versions of) check_nrpe 3.x.

I also tried `check_nrpe --v2-packets-only` or `check_nrpe -2` but that does not fix it :(

THX

Sven

**Comment by sni** [comment]
Hi sven, you can always put additional plugins into ./local/lib/nagios/plugins
I am not aware of any issues with check_nrpe so far, can you name some clients which do not work?
And tbh, this should either be fixed in `check_nrpe` or the client, or both :-)

**Comment by sni** [comment]
i gonna close this one, nrpe 2 is not maintained and does not compile with recent openssl versions. If you need check_nrpe v2, simply put it in your `local/lib/monitoring-plugins/` folder.
