### ISSUE TITLE
Logos won't load in OMD Labs Edition 3.00

### ISSUE THREAD

**Issue by dsieborger** [ConSol/omd#78]
The RewriteRules here aren't working for me:

https://github.com/ConSol/omd/blob/009c9d8767d0ca0b3729bdb0a13f50778b8300fd/packages/logos/skel/etc/apache/conf.d/logos.conf#L7-L12

I get a 404 error:

> Not Found
> 
> The requested URL /omd/sites/_SITE_/share/logos/satellite.png was not found on this server.

The reason is that Apache httpd won't treat the substitution as an absolute file path unless the RewriteRule is within a \<VirtualHost\> and that isn't the case, at least in my instance.  From http://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewriterule:

> file-system path
>    Designates the location on the file-system of the resource to be delivered to the client. Substitutions are **only treated as a file-system path when the rule is configured in server (virtualhost) context** and the first component of the path in the substitution exists in the file-system

The best solution I've been able to come up with is to rewrite them to unique URLs then resolve those to file paths with an Alias, but it's a bit messy:

```apache
RewriteCond "${OMD_ROOT}/local/share/logos/$1" "-f"
RewriteRule "^/${OMD_SITE}/logos/(.*)" "/${OMD_SITE}/local-share-logos/$1"
RewriteRule "^/${OMD_SITE}/logos/(.*)" "/${OMD_SITE}/share-logos/$1"

Alias "/${OMD_SITE}/local-share-logos" "${OMD_ROOT}/local/share/logos"
Alias "/${OMD_SITE}/share-logos" "${OMD_ROOT}/share/logos"
```

The same applies to the /SITE/nagios/images/ RewriteRule, too.

**Comment by sni** [comment]
strange, we even have a unit test for this.

**Comment by mcfone** [comment]
I'm also having the same issue after upgrading fromOMD Labs Edition 2.9 to 3.0 running on Ubuntu 16.04.6 LTS with Apache 2.4.18, and can confirm the workaround.

**Comment by sni** [comment]
The issue is not the missing virualserver. i would understand

> is configured in server (virtualhost) context

that server context is ok as well. And in fact, the issue occurs only in combination with the thruk cookie auth. Thats also the reason why our unit test did not cover this.
The solution is simply adding the [L] flag which makes them the last rule applied, see 16b650b190047e8f807cb4d7c884143a874749a1

**Comment by dsieborger** [comment]
That is much simpler and I've confirmed that it does work here.

Thanks very much.

**Comment by mcfone** [comment]
Indeed - all good now, and thanks for the quick response.

Regards,

Mark

________________________________

**Comment by ghalse** [comment]
I can confirm that this happens when thruk cookie auth is enabled, and that the [L] flag fix resolves it for us too.
