### ISSUE TITLE
PNP4Nagios PHP Session fix not included

### ISSUE THREAD

**Issue by infraweavers** [ConSol/omd#79]
Hiya,

We fixed https://github.com/lingej/pnp4nagios/pull/156 in November, is there something specific/special that needs to be done to get that included in OMD? I can't see it in 2.9 or 3.0

Many Thanks
Rob

**Comment by sni** [comment]
There had be no release of pnp4nagios since then. However, we could add patches here until
https://github.com/ConSol/omd/tree/labs/packages/pnp4nagios/patches
there is a new upstream release.

**Comment by infraweavers** [comment]
Like so? https://github.com/ConSol/omd/pull/80

**Comment by sni** [comment]
exactly
