### ISSUE TITLE
CentOS7 omd.service disabled after upgrade

### ISSUE THREAD

**Issue by ghciv6** [ConSol/omd#82]
the behaviour of my several CentOS7 installations is:
 any update of omd will disable the systemd omd.service

i noticed it first while updating to omd-2.90-1

i've checked the rpm and think the issue is in the package https://labs.consol.de/repo/stable/rhel7/x86_64/omd-3.10-labs-edition-rhel7.x86_64.rpm in the postinstall scriptlet.

```
      if [ $1 -eq 1 ] ; then
        # Initial installation
        systemctl preset omd.service >/dev/null 2>&1 || :
      fi
```
```
rpm -qip omd-3.10-labs-edition-rhel7.x86_64.rpm
    #   Name        : omd-3.10-labs-edition
    #   Version     : el7
    #   Release     : 1
    #   Architecture: x86_64
```

the package base name is "omd-3.10-labs-edition". The previous package name was "omd-3.00-labs-edition". This might be an update for humans, but not from RPM view. For RPM an update keeps the base name and increments Version and/or Release.

based on this new installed rpm package, RPM will call the postinstall scriptlet always with argument "1". this means there is only one package named "omd-3.10-labs-edition" or simplified: "this is an install, not an upgrade".

the scriptlet will always execute "systemctl preset omd.service". Cause the vendor preset is set to disabled, "systemctl preset omd.service" will always disable the omd service at install time.

```
$ systemctl enable omd   # admin enabled service
Created symlink from /etc/systemd/system/multi-user.target.wants/omd.service to /usr/lib/systemd/system/omd.service.

$ systemctl status omd
● omd.service - OMD
   Loaded: loaded (/usr/lib/systemd/system/omd.service; **enabled**; vendor preset: disabled)

$ systemctl preset omd.service  # command executed by rpm scriptlet
Removed symlink /etc/systemd/system/multi-user.target.wants/omd.service.

$ systemctl status omd
● omd.service - OMD
   Loaded: loaded (/usr/lib/systemd/system/omd.service; **disabled**; vendor preset: disabled)

```

**Comment by sni** [comment]
thanks, i thought this had been fixed already, but it seems not. I will have a look.

**Comment by sni** [comment]
should hopefully be fixed now.
