### ISSUE TITLE
When setting APACHE_TCP_ADDR to not 127.0.0.1 or 0.0.0.0, login is broken

### ISSUE THREAD

**Issue by gr4ssi** [ConSol/omd#83]
I set the tcp_addr to the local lan IP, I managed to load Thruk login page, but it threw an error, (check the logs!).

I then changed the listening addess to 0.0.0.0 and it worked.

I think the website tries to load something from localhost, but when localhost doesn't listen anymore, this fails.

`                                        '_method' => 'POST',
                                        '_uri' => bless( do{\(my $o = 'https://127.0.0.1:5000/demosite/thruk/cgi-bin/restricted.cgi')}, 'URI::https' )
                                      }, 'HTTP::Request' )
               }, 'HTTP::Response' );
auth: expected code 401, got 500
$VAR1 = bless( {
                 '_content' => 'Connect failed: connect: Connection refused; Connection refused at /omd/sites/demosite/lib/perl5/lib/perl5/LWP/Protocol/http.pm line 27.
',
                 '_headers' => bless( {
                                        '::std_case' => {
                                                          'client-date' => 'Client-Date',
                                                          'client-warning' => 'Client-Warning'
                                                        },
                                        'client-date' => 'Tue, 16 Jul 2019 09:53:00 GMT',
                                        'client-warning' => 'Internal response',
                                        'content-type' => 'text/plain'
                                      }, 'HTTP::Headers' ),
                 '_msg' => 'Connect failed: connect: Connection refused; Connection refused',
                 '_rc' => 500,
`

I did the "first steps" and fresh install on Centos 7 and created the demosite.

**Comment by sni** [comment]
you need to update your `cookie_auth_restricted_url` accordingly. But usually you don't have to change the listen address.

**Comment by gr4ssi** [comment]
The standard listen address is localhost, isn't it? 
Or was it just my mistake, to access the ServerIP:5000Port directly, and instead, with the ServerIP/Sitename, it would have worked?

**Comment by sni** [comment]
exactly, you usually contact the site with https://machine/sitename instead.
