### ISSUE TITLE
Icinga2 reload

### ISSUE THREAD

**Issue by Beatlor** [ConSol/omd#84]
I'see an issue with the icinga2 core and the config tool in the latest OMD 3.10. "check your configuration changes" - all ok but "reload your monitoring core" is showing "config reload failed". BTW in the config-tool I see only the Nagios config parameter not Icinga2 objects. Also the default config paths are not mapped to the Icinga paths.

**Comment by Beatlor** [comment]
After a fresh install and switched too incinga2  get " cannot read /omd/sites/bebe01/tmp/core/core.cfg: No such file or directory" in the top of thruk (after I logged in as omdadmin),

**Comment by sni** [comment]
Thruks Config Tool cannot be used with Icinga2. It is compatible with Naemon, Nagios 3, Icinga 1 and Shinken. Or basically anything which uses a Nagios/Naemon compatible configuration.

**Comment by Beatlor** [comment]
Ah ok - with Icinga1 yes and Icinga2 not. Thx for the fast answer.

**Comment by sni** [comment]
you're welcome :-)
