### ISSUE TITLE
OMD 3.10 does not support nagios CORE

### ISSUE THREAD

**Issue by Velociraptor85** [ConSol/omd#85]
https://labs.consol.de/de/omd/packages/nagios/ missleading as `omd config set CORE nagios` does not work in OMD 3.10 labs edition some hint migth be nice :) or a link to https://labs.consol.de/omd/migration_3.html

Also some docs or a link for naemon https://labs.consol.de/de/omd/packages/naemon/ would be nice

**Comment by lausser** [comment]
Done
