### ISSUE TITLE
~/var/thruk/sessions not being cleaned up

### ISSUE THREAD

**Issue by infraweavers** [ConSol/omd#88]
Hello,

We have a system that extracts the status out of thruk every minute for dashboarding and the sessions it creates in `~/var/thruk/sessions` do not seem to be getting cleaned up. This is under "OMD - Open Monitoring Distribution Version 3.10-labs-edition" version.

Thanks

**Comment by infraweavers** [comment]
@sni not sure if this issue is better raised under https://github.com/sni/Thruk or not?

**Comment by sni** [comment]
It would better fit in the Thruk repo. Anyway, this should be fixed with the next release, since there will be a upper limit of sessions per user and they get cleaned faster then.
