### ISSUE TITLE
nsca.cfg: "command_file" hardcoded to ~site/tmp/run/nagios.cmd

### ISSUE THREAD

**Issue by wAmpIre** [ConSol/omd#94]
Hi!

"`command_file`" in `~/etc/nsca/nsca.cfg` is hardcoded to `~/tmp/run/nagios.cmd`

As there's no more Nagios core in OMD it should be (at least) changed to `~/tmp/run/naemon.cmd` or make it an config option.

THX

Sven

**Comment by sni** [comment]
you are right, thanks
