### ISSUE TITLE
OMD distributed with grafana graphs 

### ISSUE THREAD

**Issue by Beatlor** [ConSol/omd#97]
Hello i just prepared a distributed OMD system with three nodes on CentOS 8 machines.
First I realized that the packet perl-CGI must be also be installed and is not part of the rpm dependencies  But that's not the issue I have.

I try to visualize all grafana graphs inside the master's web site. Two nodes are connected via http backends to the master. and all is working fine so far also fixed the https issue inside the backend setting. 

For example when I open a remote monitored host on the master it opens the graph from the latency of the host but there comes an error up "Annotation Query Failed" but it also shown a network issue "Network Error: undefined(undefined)". On both nodes influxdb are open to 0.0.0.0 instead of 127.0.0.1 and
I see all requests on the node coming from the master in the influxdb.log. Sounds all good so far but no graphs on the (remote) master. All http responses are 200 als not an issue. So again I see all influxqueries on the node coming from the master. On the master I see no errors in the logs.

Any idea?

BTW: LDAP authentication against Windows AD is also working fine. Maybe A HowTo would be nice for the community? (Missing package  perl-Module-Load)

Found intresting: https://github.com/grafana/grafana/issues/7896 but did not see this in my logs.

**Comment by sni** [comment]
no idea, you could try grafanas query instector.
The dependencies have been fixed in master/nightly.
Closing, since this does not seem to be a OMD issue.
