### ISSUE TITLE
Updating Prometheus directly

### ISSUE THREAD

**Issue by luxzg** [ConSol/omd#99]
Hi all,
just a question. 

Is there any expected issue from updating the prometheus executable in:
/omd/sites/site-name/bin/prometheus

with latest prometheus executable available from:
https://github.com/prometheus/prometheus/releases

I am having some weird issues where packaged prometheus just stops (no errors), and I'd just like to check if it's maybe something that newer prometheus release solved already. But I'm not comfortable of doing such changes in large package like OMD as I don't want everything to crash and burn suddenly... so a "go ahead" would be welcome, if there are no known "crash and burn" issues from that action.

Thanks!

**Comment by sni** [comment]
you can do that in a test setup, otherwise you should not touch files owned by root (which includes this one).
The OMD way would to install prometheus into ~/local/... and change the init script.

**Comment by luxzg** [comment]
OK, noted, I will do a clone of monitoring VM, change in bin/ folder, and if it looks ok-ish (no crashes), I will make a change through init script. Thanks for your help!
